import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFExporter} from './vendor/GLTFExporter.js';
import {createModel} from './model.js?v=20260910-7';
import {narration} from './narration.js?v=20260910-7';
import {EffectComposer} from './vendor/effects/postprocessing/EffectComposer.js';
import {RenderPass} from './vendor/effects/postprocessing/RenderPass.js';
import {SSAOPass} from './vendor/effects/postprocessing/SSAOPass.js';
import {OutputPass} from './vendor/effects/postprocessing/OutputPass.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const host=$('#canvas'),scene=new T.Scene(),model=createModel(),machine=model.root,parts=model.parts;
scene.add(machine);const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.87;host.replaceChildren(renderer.domElement);
const camera=new T.OrthographicCamera(-3,3,2,-2,.01,80),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minZoom=.35;controls.maxZoom=4;controls.maxPolarAngle=Math.PI*.94;controls.target.set(.10,1.52,0);
scene.add(new T.HemisphereLight(0xffffff,0x757d73,1.1));
const studio=new T.Scene();studio.background=new T.Color(0xb6bdb7);for(const [x,y,z,w,h] of [[0,6,0,7,5],[-5,2,2,3,6],[4,3,-2,4,5]]){const panel=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:new T.Color(2.5,2.5,2.5),side:T.DoubleSide}));panel.position.set(x,y,z);panel.lookAt(0,0,0);studio.add(panel);}const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(studio,.04).texture;pmrem.dispose();
const sun=new T.DirectionalLight(0xfffbef,2.4);sun.position.set(-3,7,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-4,right:4,top:4,bottom:-4,near:.2,far:20});sun.shadow.normalBias=.004;sun.shadow.bias=-.00015;scene.add(sun);
const fill=new T.DirectionalLight(0xe1eaf2,.7);fill.position.set(4,3,0);scene.add(fill);const rim=new T.DirectionalLight(0xffffff,.8);rim.position.set(0,5,-4);scene.add(rim);
const frontFill=new T.DirectionalLight(0xffffff,.9);frontFill.position.set(0,2,9);scene.add(frontFill);
const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-.03;floor.receiveShadow=true;scene.add(floor);
scene.background=new T.Color(2,2,2);
const composer=new EffectComposer(renderer),ao=new SSAOPass(scene,camera,1,1);ao.ssaoMaterial.defines.PERSPECTIVE_CAMERA=0;ao.depthRenderMaterial.defines.PERSPECTIVE_CAMERA=0;ao.kernelRadius=.10;ao.minDistance=.00005;ao.maxDistance=.004;composer.renderTarget1.samples=4;composer.renderTarget2.samples=4;composer.addPass(new RenderPass(scene,camera));composer.addPass(ao);composer.addPass(new OutputPass());
let mode='full',explode=0,selected=null,isolated=null,stage=-1,view='home';
const playback={playing:false,time:0,duration:narration.duration,speed:1};
const voice=new Audio('assets/narration.m4a?v=20260910-7');voice.preload='auto';voice.volume=.9;voice.preservesPitch=true;let playRequest=0;
const lessons=[
  ['棉箱喂入','喂棉与开松','棉箱给棉罗拉','棉层先被定量喂入，开松打手松解棉块，再沿下棉箱形成均匀棉层。','观察：棉层沿左侧通道向下移动。'],
  ['三刺辊开松','三刺辊分梳','第三刺辊','给棉罗拉握持棉层，三只刺辊逐级开松、分梳和转移纤维；除尘刀与吸口排出杂质。','观察：三刺辊交接处与下方吸口。'],
  ['锡林与盖板','锡林与盖板','锡林','锡林针布携带纤维经过固定盖板、回转盖板。针齿之间的相对运动使纤维分离、伸直和平行。','观察：纤维沿锡林外表面经过上部盖板区。'],
  ['道夫成网','道夫与成条','道夫','道夫从锡林接取纤维，在表面凝聚成薄棉网。剥棉罗拉将棉网连续剥取。','观察：右下方道夫与剥棉罗拉的交接。'],
  ['集束成条','道夫与成条','棉网集束器','棉网经过轧辊后逐渐收拢，通过集束器和大压辊压成连续棉条。','观察：宽棉网在右侧变成细棉条。'],
  ['圈条入筒','圈条机构','圈条盘','棉条经过导条架，进入圈条盘。偏心出口旋转，并与条筒运动配合，将棉条有规律地铺放。','观察：上方圈条盘与筒内的环形棉条。']
];
lessons.forEach((l,i)=>l[3]=narration.chapters[i].text);
function stageAt(t){return Math.max(0,narration.chapters.findLastIndex(c=>t>=c.start));}
function visible(p){if(p.hidden||(isolated&&isolated!==p))return false;if(p.kind==='rearShell')return mode!=='drive';if(p.kind==='cap')return mode==='full';if(p.kind==='shell')return mode==='full'||mode==='xray';return true;}
function refresh(){for(const p of parts){p.g.visible=visible(p);p.g.position.copy(p.base).addScaledVector(p.v,explode);p.g.traverse(m=>{if(!m.isMesh)return;if(!m._baseMaterial)m._baseMaterial=m.material;if(mode==='xray'&&['shell','rearShell'].includes(p.kind)){if(!m._xray){m._xray=m._baseMaterial.clone();m._xray.transparent=true;m._xray.opacity=.10;m._xray.depthWrite=false;}m.material=m._xray;m.castShadow=false;}else{m.material=m._baseMaterial;m.castShadow=true;}});}$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));fiberFlow.visible=mode!=='full'&&explode===0&&!isolated;renderList();}
const highlight=new T.BoxHelper(new T.Object3D(),0x87ab56);highlight.visible=false;scene.add(highlight);
function select(p){selected=p;$('#part-name').textContent=p.name;$('#part-desc').textContent=p.desc;$('#selected-actions').hidden=false;highlight.setFromObject(p.g);highlight.visible=true;renderList();}
function renderList(){const query=$('#search').value.trim(),list=$('#parts'),open=new Set([...list.querySelectorAll('details[open]')].map(d=>d.dataset.section));list.replaceChildren();for(const sec of model.sections){const found=parts.filter(p=>p.section===sec&&(!query||p.name.includes(query)));if(!found.length)continue;const d=document.createElement('details');d.dataset.section=sec;d.open=!!query||open.has(sec);const s=document.createElement('summary');s.textContent=sec+' · '+found.length;s.className='group-title';d.append(s);for(const p of found){const b=document.createElement('button');b.className='partrow'+(p===selected?' active':'');b.innerHTML='<i></i><span></span><small></small>';b.querySelector('span').textContent=p.name;b.querySelector('small').textContent=p.hidden?'已隐藏':'';b.onclick=()=>{isolated=null;p.hidden=false;if(['shell','rearShell','cap'].includes(p.kind))mode='full';else if(p.kind==='motor'){mode='drive';setView('back');}refresh();select(p);};d.append(b);}list.append(d);}}
function setView(v){view=v;const positions={home:[-.5,3.05,9],side:[.10,1.52,9],front:[9,2.5,0],back:[.10,1.52,-9],left:[-9,1.6,0],left45:[-6,3.9,7],right45:[6,3.9,7],top:[.10,10,.001]};controls.target.set(.10,1.52,0);camera.position.set(...positions[v]);camera.zoom=['left45','right45'].includes(v)?.76:v==='top'?.78:.90;controls.update();camera.updateProjectionMatrix();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));}
function fitSelected(){const b=new T.Box3().setFromObject(selected.g),c=b.getCenter(new T.Vector3()),sz=b.getSize(new T.Vector3());controls.target.copy(c);camera.position.copy(c).add(new T.Vector3(.5,.4,4));camera.zoom=Math.min(3,4/Math.max(sz.x,sz.y,sz.z));controls.update();camera.updateProjectionMatrix();}
function pause(){playRequest++;voice.pause();playback.playing=false;$('#play-toggle').textContent='▶ 播放原理';$('#play-state').textContent='已暂停';}
function restore(){isolated=null;parts.forEach(p=>p.hidden=false);refresh();}
function reset(){pause();$('#caption').hidden=true;playback.time=0;stage=-1;mode='full';explode=0;$('#explode').value=0;$('#amount').textContent='0%';selected=null;highlight.visible=false;restore();setView('home');updateMotion(0);$('#part-name').textContent='梳棉机 · 剖视结构';$('#part-desc').textContent='拖动旋转查看筒体深度，点击每个零件查看功能；从原理课堂开始连续讲解。';$('#selected-actions').hidden=true;seek(0);}
$$('[data-mode]').forEach(b=>b.onclick=()=>{pause();const wasDrive=mode==='drive';mode=b.dataset.mode;if(mode==='drive')setView('back');else if(wasDrive)setView('home');isolated=null;highlight.visible=false;refresh();});$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#reset').onclick=reset;
$('#explode').oninput=e=>{pause();explode=Number(e.target.value)/100;$('#amount').textContent=e.target.value+'%';highlight.visible=false;refresh();};$('#search').oninput=renderList;
$('#isolate').onclick=()=>{pause();isolated=selected;refresh();fitSelected();};$('#hidepart').onclick=()=>{selected.hidden=true;highlight.visible=false;refresh();};$('#restore').onclick=restore;
const ray=new T.Raycaster(),mouse=new T.Vector2();let down;
renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=host.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(parts.filter(p=>p.g.visible).map(p=>p.g),true)[0];if(hit){const p=parts.find(p=>p.g.name===hit.object.userData.partId);if(p)select(p);}});
// 时间轴支持确定性拖动和续播，运动轴保留用于动画导出。
const playbackUI=document.createElement('div');playbackUI.className='playback';playbackUI.innerHTML='<div class="playback-head"><strong id="playback-title">棉箱喂入</strong><time id="playback-time"></time></div><div class="playback-controls"><button id="play-toggle">▶ 播放原理</button><button id="play-prev" aria-label="上一工序">‹</button><button id="play-next" aria-label="下一工序">›</button><select id="speed" aria-label="播放速度"><option value="0.5">0.5 倍</option><option value="1" selected>1 倍</option><option value="1.5">1.5 倍</option></select></div><input id="play-progress" type="range" min="0" max="'+playback.duration+'" step="0.05" value="0" aria-label="原理播放进度"><div class="sound-controls"><button id="sound-toggle" aria-pressed="true">🔊 讲解声音：开</button><label>音量<input id="volume" type="range" min="0" max="1" step="0.05" value="0.9" aria-label="讲解音量"></label></div><div class="playback-head"><span id="play-state">点击播放，即可听讲解</span><span class="muted">普通话女声</span></div><p id="play-caption"></p>';
$('#lesson').insertBefore(playbackUI,$('#steps'));
function fmt(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function setPlaybackTime(t){playback.time=Math.max(0,Math.min(playback.duration,t));const i=stageAt(playback.time);$('#play-progress').value=playback.time;$('#playback-time').textContent=fmt(playback.time)+' / '+fmt(playback.duration);if(stage!==i){stage=i;$('#playback-title').textContent=lessons[i][0];$('#play-caption').textContent=lessons[i][3];$('#caption-title').textContent=`0${i+1} / ${lessons[i][0]}`;$('#caption-text').textContent=lessons[i][4];$$('[data-step]').forEach(b=>b.classList.toggle('active',+b.dataset.step===i));}updateMotion(playback.time);}
function seek(t){voice.currentTime=Math.max(0,Math.min(playback.duration,t));setPlaybackTime(t);}
function lesson(i){pause();if(mode==='drive')setView('home');mode='open';explode=0;$('#explode').value=0;$('#amount').textContent='0%';restore();setView('home');highlight.visible=false;seek(narration.chapters[i].start);$('#caption').hidden=false;}
$('#play-toggle').onclick=async()=>{if(playback.playing){pause();return;}if(playback.time>=playback.duration)seek(0);if(mode==='drive')setView('home');mode='open';explode=0;$('#explode').value=0;$('#amount').textContent='0%';restore();highlight.visible=false;const request=++playRequest;voice.currentTime=playback.time;voice.playbackRate=playback.speed;$('video').pause();playback.playing=true;$('#play-toggle').textContent='Ⅱ 暂停';$('#play-state').textContent='正在载入讲解…';$('#caption').hidden=false;try{await voice.play();if(request===playRequest)$('#play-state').textContent=voice.muted?'正在播放 · 已静音':'正在播放 · 女声讲解';}catch(e){if(request!==playRequest)return;pause();$('#play-state').textContent='声音加载失败，请重新播放';toast('讲解声音未能播放，请检查网络后重试');}};
$('#play-prev').onclick=()=>lesson(Math.max(0,stageAt(playback.time)-1));$('#play-next').onclick=()=>lesson(Math.min(5,stageAt(playback.time)+1));
$('#play-progress').oninput=e=>{pause();if(mode==='drive')setView('home');mode='open';explode=0;$('#explode').value=0;$('#amount').textContent='0%';restore();seek(+e.target.value);$('#caption').hidden=false;};$('#speed').onchange=e=>{playback.speed=+e.target.value;voice.playbackRate=playback.speed;};
function updateSound(){const on=!voice.muted&&voice.volume>0;$('#sound-toggle').textContent=on?'🔊 讲解声音：开':'🔇 讲解声音：关';$('#sound-toggle').setAttribute('aria-pressed',String(on));if(playback.playing)$('#play-state').textContent=on?'正在播放 · 女声讲解':'正在播放 · 已静音';}
$('#sound-toggle').onclick=()=>{if(voice.volume===0){voice.volume=.9;$('#volume').value=.9;voice.muted=false;}else voice.muted=!voice.muted;updateSound();};$('#volume').oninput=e=>{voice.volume=+e.target.value;voice.muted=voice.volume===0;updateSound();};
voice.addEventListener('waiting',()=>{if(playback.playing)$('#play-state').textContent='正在缓冲讲解…';});voice.addEventListener('playing',updateSound);voice.addEventListener('ended',()=>{pause();setPlaybackTime(playback.duration);$('#play-toggle').textContent='↻ 重播';$('#play-state').textContent='播放结束';});voice.addEventListener('error',()=>{pause();$('#play-state').textContent='讲解音频加载失败，请刷新重试';});$('video').addEventListener('play',pause);
lessons.forEach((l,i)=>{const b=document.createElement('button');b.className='step';b.dataset.step=i;b.innerHTML=`<b>0${i+1}</b><span>${l[0]}</span>`;b.onclick=()=>lesson(i);$('#steps').append(b);const f=document.createElement('button');f.textContent=l[0];f.dataset.step=i;f.onclick=()=>{$('[data-tab="lesson"]').click();lesson(i);};$('#flow').append(f);if(i<5){const s=document.createElement('span');s.textContent='→';$('#flow').append(s);}});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#structure').hidden=b.dataset.tab!=='structure';$('#lesson').hidden=b.dataset.tab!=='lesson';});
const fiberFlow=new T.Group();fiberFlow.name='教学纤维运动';machine.add(fiberFlow);const fiberMat=new T.LineBasicMaterial({color:0xf6b73b,transparent:true,opacity:.90});
const strands=[];for(let i=0;i<100;i++){const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(new Float32Array(18),3));const line=new T.Line(geometry,fiberMat);line.frustumCulled=false;fiberFlow.add(line);strands.push(line);}
const arrowGroup=new T.Group();fiberFlow.add(arrowGroup);
for(const name of ['锡林','道夫','第一刺辊','第二刺辊','第三刺辊']){const p=parts.find(p=>p.name===name),r=name==='锡林'?.57:name==='道夫'?.31:.065,direction=model.rotors.find(r=>r.p===p)?.speed>0?1:-1,c=new T.EllipseCurve(0,0,r,r,0,direction*Math.PI*.60,direction<0,0),pts=c.getPoints(40).map(v=>new T.Vector3(v.x,v.y,.54));const a=new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:0xb27c21,transparent:true,opacity:.72}));a.position.copy(p.base);arrowGroup.add(a);const head=new T.Mesh(new T.ConeGeometry(.019,.05,3),new T.MeshBasicMaterial({color:0xb27c21}));head.position.copy(p.base).add(new T.Vector3(pts.at(-1).x,pts.at(-1).y,.54));head.rotation.z=direction*Math.PI*.60+(direction<0?Math.PI:0);arrowGroup.add(head);}
for(const f of model.flats){let best=Infinity;for(let j=0;j<600;j++){const d=model.flatLoop.getPointAt(j/600).distanceToSquared(f.p.base);if(d<best){best=d;f.baseU=j/600;}}}
function updateMotion(t){for(const {p,speed,axis='z'} of model.rotors)p.g.rotation[axis]=p.rotation[axis]+t*speed;if(t===0){for(const f of model.flats){f.p.g.position.copy(f.p.base).addScaledVector(f.p.v,explode);f.p.g.rotation.copy(f.p.rotation);}}else for(const f of model.flats){const u=(f.baseU+t*.0015)%1,v=model.flatLoop.getPointAt(u),tan=model.flatLoop.getTangentAt(u);f.p.g.position.copy(v).addScaledVector(f.p.v,explode);f.p.g.rotation.z=Math.atan2(tan.y,tan.x);}model.updateCoilerThread(t);const stageIndex=stageAt(t),curve=model.flowStages[stageIndex];strands.forEach((line,i)=>{const data=line.geometry.attributes.position,q=(t*.13+i/100)%1;for(let j=0;j<6;j++){const u=Math.max(0,Math.min(.999,q-j*.0008)),v=curve.getPointAt(u);data.setXYZ(j,v.x,v.y,stageIndex===5?v.z+.015:.545+(i%5)*.001);}data.needsUpdate=true;line.visible=t>0;});arrowGroup.visible=t>0;}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
$('#export').onclick=async()=>{const button=$('#export');button.disabled=true;button.textContent='正在导出…';pause();model.updateCoilerThread(0);try{const clone=new T.Group();clone.name=machine.name;for(const p of parts){const g=p.g.clone(true);g.position.copy(p.base);g.rotation.copy(p.rotation);g.visible=true;g.traverse(m=>{if(m.isMesh){if(p.name==='圈条盘入筒棉条')m.geometry=m.geometry.clone();m.material=(m._baseMaterial||m.material).clone();m.material.transparent=false;m.material.opacity=1;delete m._baseMaterial;delete m._xray;}});clone.add(g);}const data=await new GLTFExporter().parseAsync(clone,{binary:true,onlyVisible:false}),url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'})),a=document.createElement('a');a.href=url;a.download='梳棉机-独立零件-参考图重建.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('已导出独立零件、装配坐标和动画转轴');}catch(e){console.error(e);toast('导出失败，请重试');}finally{model.updateCoilerThread(playback.time);button.disabled=false;button.textContent='↓ 导出模型';}};
$('#compare').onclick=()=>$('#reference-dialog').showModal();$('#close-reference').onclick=()=>$('#reference-dialog').close();$('#reference-dialog').addEventListener('click',e=>{if(e.target===$('#reference-dialog'))$('#reference-dialog').close();});
function resize(){const r=host.getBoundingClientRect(),aspect=r.width/r.height;renderer.setSize(r.width,r.height);composer.setSize(r.width,r.height);const h=Math.max(3.85,5.3/aspect);camera.left=-h*aspect/2;camera.right=h*aspect/2;camera.top=h/2;camera.bottom=-h/2;camera.updateProjectionMatrix();}
new ResizeObserver(resize).observe(host);$('#count').textContent=parts.length+' 个独立展示件';setView('home');resize();refresh();setPlaybackTime(0);
renderer.setAnimationLoop(()=>{if(playback.playing)setPlaybackTime(voice.currentTime);controls.update();if(highlight.visible&&selected)highlight.setFromObject(selected.g);if(innerWidth>680&&mode!=='xray'){ao.ssaoMaterial.uniforms.cameraProjectionMatrix.value.copy(camera.projectionMatrix);ao.ssaoMaterial.uniforms.cameraInverseProjectionMatrix.value.copy(camera.projectionMatrixInverse);composer.render();}else renderer.render(scene,camera);});
window.trainingModel={scene,machine,parts,renderer,camera,controls,setView,refresh,select,lesson,model,playback,narration,voice,stageAt,setPlaybackTime,reset,getState:()=>({mode,explode,isolated:isolated?.name,view})};
