function numericFamily(config) {
  return config.cases.map((item, index) => ({
    id: `QB-${config.code}-${String(index + 1).padStart(2, "0")}`,
    subject: config.subject,
    skill: config.skill,
    title: item.title || config.title,
    stem: item.stem,
    type: "numeric",
    answer: item.answer,
    acceptable: item.acceptable || [String(item.answer)],
    difficulty: item.difficulty || config.difficulty || 2,
    points: config.points || (config.subject === "physics" ? 6 : 5),
    estimatedSeconds: item.estimatedSeconds || config.estimatedSeconds || 100,
    hints: item.hints || config.hints,
    explanation: {
      idea: item.idea || config.idea,
      steps: item.steps,
      trap: item.trap || config.trap,
    },
    sourceType: "stable-variant",
  }));
}

function choiceFamily(config) {
  return config.cases.map((item, index) => ({
    id: `QB-${config.code}-${String(index + 1).padStart(2, "0")}`,
    subject: config.subject,
    skill: config.skill,
    title: item.title || config.title,
    stem: item.stem,
    type: "choice",
    options: item.options,
    answer: item.answer,
    difficulty: item.difficulty || config.difficulty || 2,
    points: config.points || 5,
    estimatedSeconds: item.estimatedSeconds || config.estimatedSeconds || 90,
    hints: item.hints || config.hints,
    explanation: {
      idea: item.idea || config.idea,
      steps: item.steps,
      trap: item.trap || config.trap,
    },
    errorByChoice: item.errorByChoice || config.errorByChoice,
    sourceType: "stable-variant",
  }));
}

const MATH_FAMILIES = [
  ...numericFamily({
    code: "M-QUAD",
    subject: "math",
    skill: "quadratic",
    title: "韦达定理快速取值",
    idea: "不必先求两个根，直接从系数读取根的和或积。",
    hints: ["先确认方程已经写成 ax²+bx+c=0。", "两根和为 −b/a，两根积为 c/a。", "注意 b 本身可能带负号。"],
    trap: "最常见错误是漏掉根的和公式前面的负号。",
    cases: [
      { stem: "方程 x²−5x+6=0 的两个实根之和是多少？", answer: 5, steps: ["a=1，b=−5。", "x₁+x₂=−b/a。", "所以两根之和为 5。"] },
      { stem: "方程 2x²−7x+3=0 的两个实根之和是多少？可填分数。", answer: 3.5, acceptable: ["3.5", "7/2"], steps: ["a=2，b=−7。", "x₁+x₂=−(−7)/2。", "结果为 7/2。"] },
      { stem: "方程 x²+4x−5=0 的两个实根之和是多少？", answer: -4, steps: ["a=1，b=4。", "使用 x₁+x₂=−b/a。", "结果为 −4。"] },
      { stem: "方程 3x²+x−2=0 的两个实根之积是多少？可填分数。", answer: -2 / 3, acceptable: ["-2/3", "−2/3", "-0.6666667"], steps: ["a=3，c=−2。", "x₁x₂=c/a。", "结果为 −2/3。"] },
    ],
  }),
  ...choiceFamily({
    code: "M-DOMAIN",
    subject: "math",
    skill: "function",
    title: "函数定义域",
    idea: "定义域来自使每一个表达式都有意义的条件交集。",
    hints: ["根号内要求不小于 0。", "对数真数要求大于 0，分母要求不为 0。", "多个条件要取交集。"],
    trap: "根号条件是“≥0”，对数真数条件是“>0”，不要混用。",
    cases: [
      { stem: "函数 f(x)=√(2−x) 的定义域是（　）", options: ["(−∞,2]", "[2,+∞)", "(−∞,2)", "(2,+∞)"], answer: 0, steps: ["根号内 2−x≥0。", "解得 x≤2。", "定义域为 (−∞,2]。"] },
      { stem: "函数 f(x)=ln(x−1) 的定义域是（　）", options: ["[1,+∞)", "(1,+∞)", "(−∞,1)", "(−∞,1]"], answer: 1, steps: ["对数真数 x−1>0。", "解得 x>1。", "定义域为 (1,+∞)。"] },
      { stem: "函数 f(x)=1/(x+3) 的定义域是（　）", options: ["R", "(−3,+∞)", "R\{−3}", "(−∞,−3)"], answer: 2, steps: ["分母 x+3≠0。", "所以 x≠−3。", "定义域为 R\{−3}。"] },
      { stem: "函数 f(x)=√(x+2)/(x−1) 的定义域是（　）", options: ["[−2,+∞)", "[−2,1)", "[−2,1)∪(1,+∞)", "(−2,1)∪(1,+∞)"], answer: 2, steps: ["根号要求 x≥−2。", "分母要求 x≠1。", "取交集得 [−2,1)∪(1,+∞)。"] },
    ],
  }),
  ...numericFamily({
    code: "M-DERIV",
    subject: "math",
    skill: "derivative",
    title: "导数求切线斜率",
    idea: "曲线上 x=x₀ 处的切线斜率就是 f′(x₀)。",
    hints: ["先求导函数。", "再把指定的 x 代入导函数。", "不要把原函数值当成斜率。"],
    trap: "求的是 f′(x₀)，不是 f(x₀)。",
    cases: [
      { stem: "曲线 y=x²−4x 在 x=3 处的切线斜率是多少？", answer: 2, steps: ["y′=2x−4。", "代入 x=3。", "斜率 k=2。"] },
      { stem: "曲线 y=x³ 在 x=2 处的切线斜率是多少？", answer: 12, steps: ["y′=3x²。", "代入 x=2。", "k=3×4=12。"] },
      { stem: "曲线 y=2x²−3x+1 在 x=0 处的切线斜率是多少？", answer: -3, steps: ["y′=4x−3。", "代入 x=0。", "k=−3。"] },
      { stem: "曲线 y=1/x 在 x=1 处的切线斜率是多少？", answer: -1, steps: ["y=x⁻¹，所以 y′=−x⁻²。", "代入 x=1。", "k=−1。"] },
    ],
  }),
  ...numericFamily({
    code: "M-ARITH",
    subject: "math",
    skill: "sequence",
    title: "等差数列通项与求和",
    idea: "先识别首项、公差与项数，再选通项或求和公式。",
    hints: ["第 n 项比首项多 n−1 个公差。", "aₙ=a₁+(n−1)d。", "Sₙ=n(a₁+aₙ)/2。"],
    trap: "从第 1 项到第 n 项只有 n−1 个公差。",
    cases: [
      { stem: "等差数列中 a₁=2，d=3，求 a₁₀。", answer: 29, steps: ["a₁₀=a₁+9d。", "代入 2+9×3。", "a₁₀=29。"] },
      { stem: "等差数列中 a₁=5，d=−2，求 a₈。", answer: -9, steps: ["a₈=a₁+7d。", "代入 5+7×(−2)。", "a₈=−9。"] },
      { stem: "等差数列 1,4,7,… 的前 20 项和是多少？", answer: 590, steps: ["a₂₀=1+19×3=58。", "S₂₀=20×(1+58)/2。", "S₂₀=590。"] },
      { stem: "等差数列中 a₁=4，a₁₅=32，求 S₁₅。", answer: 270, steps: ["直接用首末项求和。", "S₁₅=15×(4+32)/2。", "S₁₅=270。"] },
    ],
  }),
  ...numericFamily({
    code: "M-GEO",
    subject: "math",
    skill: "geometric-sequence",
    title: "等比数列",
    idea: "相邻项的固定倍数是公比，通项中指数为 n−1。",
    hints: ["先确认公比 q。", "aₙ=a₁qⁿ⁻¹。", "有限和可用首项乘 1−qⁿ 再除以 1−q。"],
    trap: "通项的指数是 n−1，不是 n。",
    cases: [
      { stem: "等比数列中 a₁=3，q=2，求 a₆。", answer: 96, steps: ["a₆=3×2⁵。", "2⁵=32。", "a₆=96。"] },
      { stem: "等比数列中 a₁=81，q=1/3，求 a₅。", answer: 1, steps: ["a₅=81×(1/3)⁴。", "(1/3)⁴=1/81。", "a₅=1。"] },
      { stem: "等比数列 1,2,4,… 的前 8 项和是多少？", answer: 255, steps: ["a₁=1，q=2。", "S₈=(1−2⁸)/(1−2)。", "S₈=255。"] },
      { stem: "等比数列中 a₁=2，q=3，前 4 项和是多少？", answer: 80, steps: ["前 4 项为 2,6,18,54。", "也可用 S₄=2(1−3⁴)/(1−3)。", "结果为 80。"] },
    ],
  }),
  ...choiceFamily({
    code: "M-TRIG",
    subject: "math",
    skill: "trigonometry",
    title: "三角函数振幅",
    idea: "a sin x+b cos x 的振幅是 √(a²+b²)。",
    hints: ["把两个同频三角函数合成一个。", "先求振幅 √(a²+b²)。", "正弦或余弦部分最大值为 1。"],
    trap: "不能把 sin x 和 cos x 的最大值分别取到 1 后直接相加。",
    cases: [
      { stem: "函数 y=3sin x+4cos x 的最大值为（　）", options: ["4", "5", "7", "25"], answer: 1, steps: ["振幅为 √(3²+4²)。", "√25=5。", "最大值为 5。"] },
      { stem: "函数 y=5sin x−12cos x 的最大值为（　）", options: ["7", "12", "13", "17"], answer: 2, steps: ["振幅为 √(5²+(−12)²)。", "√169=13。", "最大值为 13。"] },
      { stem: "函数 y=sin x−cos x 的最小值为（　）", options: ["−2", "−√2", "−1", "0"], answer: 1, steps: ["振幅为 √2。", "合成后的正弦函数值域为 [−√2,√2]。", "最小值为 −√2。"] },
      { stem: "函数 y=2sin x+2cos x 的最大值为（　）", options: ["2", "2√2", "4", "√2"], answer: 1, steps: ["振幅为 √(2²+2²)。", "√8=2√2。", "最大值为 2√2。"] },
    ],
  }),
  ...numericFamily({
    code: "M-VECTOR",
    subject: "math",
    skill: "vectors",
    title: "向量数量积",
    idea: "坐标形式的数量积等于对应坐标乘积之和。",
    hints: ["若 a=(x₁,y₁)，b=(x₂,y₂)。", "a·b=x₁x₂+y₁y₂。", "垂直时数量积为 0。"],
    trap: "数量积是一个数，不是一个新向量。",
    cases: [
      { stem: "向量 a=(2,3)，b=(4,−1)，求 a·b。", answer: 5, steps: ["a·b=2×4+3×(−1)。", "计算 8−3。", "结果为 5。"] },
      { stem: "向量 a=(−1,5)，b=(3,2)，求 a·b。", answer: 7, steps: ["a·b=(−1)×3+5×2。", "计算 −3+10。", "结果为 7。"] },
      { stem: "向量 a=(1,2)，b=(x,−2)，若 a⊥b，求 x。", answer: 4, steps: ["垂直意味着 a·b=0。", "x+2×(−2)=0。", "解得 x=4。"] },
      { stem: "向量 a=(3,−4) 的模长是多少？", answer: 5, steps: ["|a|=√(3²+(−4)²)。", "根号内为 25。", "模长为 5。"] },
    ],
  }),
  ...numericFamily({
    code: "M-PROB",
    subject: "math",
    skill: "probability",
    title: "古典概型",
    idea: "概率等于有利基本事件数除以全部基本事件数。",
    hints: ["先确认所有基本事件是否等可能。", "分别数全部情况和有利情况。", "不放回抽取时总数会变化。"],
    trap: "“至少一个”常用对立事件更快。",
    cases: [
      { stem: "掷一枚均匀骰子一次，点数大于 4 的概率是多少？可填分数。", answer: 1 / 3, acceptable: ["1/3", "0.3333333"], steps: ["全部有 6 种等可能结果。", "大于 4 有 5、6 两种。", "概率为 2/6=1/3。"] },
      { stem: "从 1,2,3,4,5 中随机取一个数，取到偶数的概率是多少？", answer: 0.4, acceptable: ["2/5", "0.4", "40%"], steps: ["全部有 5 个数。", "偶数有 2、4 两个。", "概率为 2/5。"] },
      { stem: "同时抛两枚均匀硬币，恰好一枚正面朝上的概率是多少？", answer: 0.5, acceptable: ["1/2", "0.5", "50%"], steps: ["结果为正正、正反、反正、反反。", "恰好一个正面有 2 种。", "概率为 2/4=1/2。"] },
      { stem: "袋中有 3 个红球、2 个白球，不放回抽取 2 个，两球都是白球的概率是多少？", answer: 0.1, acceptable: ["1/10", "0.1", "10%"], steps: ["第一次白球概率 2/5。", "第二次白球概率 1/4。", "相乘得 1/10。"] },
    ],
  }),
  ...choiceFamily({
    code: "M-CIRCLE",
    subject: "math",
    skill: "analytic",
    title: "圆的标准方程",
    idea: "标准式 (x−a)²+(y−b)²=r² 中，圆心为 (a,b)。",
    hints: ["先与圆的标准式对照。", "圆心坐标与括号里的符号相反。", "等号右边是半径的平方。"],
    trap: "把 r² 误当半径，或把括号符号直接抄成圆心。",
    cases: [
      { stem: "圆 (x−3)²+(y+2)²=16 的圆心与半径是（　）", options: ["(3,−2)，4", "(−3,2)，4", "(3,2)，16", "(−3,−2)，8"], answer: 0, steps: ["对照 (x−a)²+(y−b)²=r²。", "a=3，b=−2。", "r=√16=4。"] },
      { stem: "圆 (x+1)²+(y−5)²=9 的圆心与半径是（　）", options: ["(1,−5)，3", "(−1,5)，3", "(−1,5)，9", "(1,5)，3"], answer: 1, steps: ["x+1=x−(−1)。", "圆心为 (−1,5)。", "半径为 3。"] },
      { stem: "圆 x²+y²=25 的圆心与半径是（　）", options: ["(0,0)，5", "(0,0)，25", "(5,5)，5", "(−5,−5)，25"], answer: 0, steps: ["方程可写为 (x−0)²+(y−0)²=25。", "圆心是原点。", "半径为 5。"] },
      { stem: "圆 (x−2)²+(y−1)²=2 的圆心与半径是（　）", options: ["(2,1)，2", "(−2,−1)，√2", "(2,1)，√2", "(1,2)，√2"], answer: 2, steps: ["圆心为 (2,1)。", "r²=2。", "所以 r=√2。"] },
    ],
  }),
  ...numericFamily({
    code: "M-VOLUME",
    subject: "math",
    skill: "geometry3d",
    title: "空间几何体体积",
    idea: "先识别几何体，再使用底面积乘高；锥体还要乘 1/3。",
    hints: ["圆柱 V=πr²h。", "圆锥 V=(1/3)πr²h。", "球 V=(4/3)πr³。"],
    trap: "注意题目要的是体积系数；答案中的 π 不要遗漏。",
    cases: [
      { stem: "圆柱底面半径为 2，高为 5，其体积是 kπ，求 k。", answer: 20, steps: ["V=πr²h。", "代入 π×2²×5。", "V=20π，所以 k=20。"] },
      { stem: "圆锥底面半径为 3，高为 8，其体积是 kπ，求 k。", answer: 24, steps: ["V=(1/3)πr²h。", "代入 (1/3)×π×9×8。", "V=24π。"] },
      { stem: "球的半径为 3，体积是 kπ，求 k。", answer: 36, steps: ["V=(4/3)πr³。", "代入 r=3。", "V=(4/3)×27π=36π。"] },
      { stem: "底面积为 12、高为 5 的三棱锥体积是多少？", answer: 20, steps: ["棱锥 V=(1/3)Sh。", "代入 (1/3)×12×5。", "体积为 20。"] },
    ],
  }),
];

const PHYSICS_FAMILIES = [
  ...numericFamily({
    code: "P-MOTION",
    subject: "physics",
    skill: "motion",
    title: "匀变速直线运动",
    idea: "先选正方向，再用速度公式 v=v₀+at。",
    hints: ["找出初速度、加速度和时间。", "速度公式 v=v₀+at。", "减速运动的加速度与速度方向相反。"],
    trap: "减速时 a 应带负号，不能只代加速度大小。",
    cases: [
      { stem: "汽车初速度 4 m/s，以 2 m/s² 加速 3 s，末速度是多少 m/s？", answer: 10, steps: ["v=v₀+at。", "v=4+2×3。", "末速度为 10 m/s。"] },
      { stem: "物体从静止开始以 3 m/s² 匀加速 4 s，末速度是多少 m/s？", answer: 12, steps: ["初速度 v₀=0。", "v=0+3×4。", "末速度为 12 m/s。"] },
      { stem: "汽车以 20 m/s 行驶，随后以 4 m/s² 匀减速，3 s 后速度是多少 m/s？", answer: 8, steps: ["取原速度方向为正，a=−4 m/s²。", "v=20−4×3。", "速度为 8 m/s。"] },
      { stem: "物体初速度 5 m/s，加速度 1.5 m/s²，经过 4 s 后速度是多少 m/s？", answer: 11, steps: ["使用 v=v₀+at。", "v=5+1.5×4。", "末速度为 11 m/s。"] },
    ],
  }),
  ...numericFamily({
    code: "P-NEWTON",
    subject: "physics",
    skill: "mechanics",
    title: "牛顿第二定律",
    idea: "先求物体受到的合力，再使用 F合=ma。",
    hints: ["画出研究对象的受力。", "同一直线反向力要相减。", "a=F合/m。"],
    trap: "不能把某一个力直接当合力。",
    cases: [
      { stem: "质量 3 kg 的物体受 15 N 水平拉力和 3 N 反向摩擦力，加速度是多少 m/s²？", answer: 4, steps: ["合力为 15−3=12 N。", "a=F合/m。", "a=12/3=4 m/s²。"] },
      { stem: "质量 5 kg 的物体所受水平合力为 20 N，加速度是多少 m/s²？", answer: 4, steps: ["已知合力 20 N。", "a=20/5。", "加速度为 4 m/s²。"] },
      { stem: "质量 2 kg 的物体在光滑水平面受 6 N 与 10 N 两个反向力，加速度大小是多少 m/s²？", answer: 2, steps: ["合力大小为 10−6=4 N。", "a=4/2。", "加速度大小为 2 m/s²。"] },
      { stem: "质量 4 kg 的物体产生 3 m/s² 加速度，需要的合力是多少 N？", answer: 12, steps: ["F合=ma。", "代入 4×3。", "合力为 12 N。"] },
    ],
  }),
  ...numericFamily({
    code: "P-PROJECT",
    subject: "physics",
    skill: "projectile",
    title: "平抛运动时间",
    idea: "平抛落地时间只由竖直高度决定，使用 h=½gt²。",
    hints: ["把运动分解为水平和竖直两个方向。", "竖直方向初速度为 0。", "取 g=10 m/s²，使用 h=5t²。"],
    trap: "求时间时不需要水平初速度。",
    cases: [
      { stem: "小球从 45 m 高处水平抛出，取 g=10 m/s²，落地时间是多少 s？", answer: 3, steps: ["竖直方向 45=5t²。", "t²=9。", "t=3 s。"] },
      { stem: "小球从 80 m 高处水平抛出，取 g=10 m/s²，落地时间是多少 s？", answer: 4, steps: ["80=5t²。", "t²=16。", "t=4 s。"] },
      { stem: "平抛小球落地用时 2 s，取 g=10 m/s²，抛出点高度是多少 m？", answer: 20, steps: ["h=5t²。", "代入 t=2。", "h=20 m。"] },
      { stem: "小球从 125 m 高处水平抛出，取 g=10 m/s²，落地时间是多少 s？", answer: 5, steps: ["125=5t²。", "t²=25。", "t=5 s。"] },
    ],
  }),
  ...numericFamily({
    code: "P-ENERGY",
    subject: "physics",
    skill: "energy",
    title: "机械能守恒",
    idea: "忽略阻力时，重力势能的减少量等于动能增加量。",
    hints: ["先确认机械能是否守恒。", "从静止下落可用 mgh=½mv²。", "质量通常可以约去。"],
    trap: "高度必须使用下降的竖直高度，不是轨迹长度。",
    cases: [
      { stem: "物体从 5 m 高处由静止下落，忽略阻力，取 g=10 m/s²，落地速度是多少 m/s？", answer: 10, steps: ["mgh=½mv²。", "2gh=v²。", "v=√(2×10×5)=10 m/s。"] },
      { stem: "物体由静止从 20 m 高处下落，忽略阻力，取 g=10 m/s²，落地速度是多少 m/s？", answer: 20, steps: ["使用 v=√(2gh)。", "2gh=400。", "v=20 m/s。"] },
      { stem: "质量 2 kg 的物体速度为 3 m/s，动能是多少 J？", answer: 9, steps: ["Eₖ=½mv²。", "代入 ½×2×3²。", "动能为 9 J。"] },
      { stem: "质量 5 kg 的物体被提升 4 m，取 g=10 m/s²，重力势能增加多少 J？", answer: 200, steps: ["ΔEₚ=mgh。", "代入 5×10×4。", "增加 200 J。"] },
    ],
  }),
  ...numericFamily({
    code: "P-MOMENTUM",
    subject: "physics",
    skill: "momentum",
    title: "动量与碰撞",
    idea: "碰撞时间很短且外力冲量可忽略时，系统总动量守恒。",
    hints: ["先规定正方向。", "写出碰前总动量。", "粘在一起后质量要相加。"],
    trap: "动量有方向，反向速度必须带负号。",
    cases: [
      { stem: "1 kg 小车以 6 m/s 撞上静止的 2 kg 小车并粘在一起，共同速度是多少 m/s？", answer: 2, steps: ["碰前动量为 1×6。", "碰后总质量 3 kg。", "3v=6，v=2 m/s。"] },
      { stem: "2 kg 小车以 3 m/s 撞上静止的 1 kg 小车并粘在一起，共同速度是多少 m/s？", answer: 2, steps: ["碰前动量为 2×3=6。", "碰后总质量 3 kg。", "v=6/3=2 m/s。"] },
      { stem: "质量 4 kg、速度 5 m/s 的物体，其动量大小是多少 kg·m/s？", answer: 20, steps: ["p=mv。", "代入 4×5。", "动量大小为 20 kg·m/s。"] },
      { stem: "1 kg 小车以 4 m/s 向右、1 kg 小车以 2 m/s 向左，相撞后粘住，共同速度向右多少 m/s？", answer: 1, steps: ["取向右为正。", "碰前总动量 1×4+1×(−2)=2。", "总质量 2 kg，v=1 m/s。"] },
    ],
  }),
  ...numericFamily({
    code: "P-CIRCUIT",
    subject: "physics",
    skill: "electricity",
    title: "电路基本计算",
    idea: "先判断串并联和等效电阻，再使用欧姆定律。",
    hints: ["串联电阻直接相加。", "并联满足 1/R=1/R₁+1/R₂。", "I=U/R，P=UI。"],
    trap: "串联和并联的等效电阻公式不要混用。",
    cases: [
      { stem: "3 Ω 与 6 Ω 电阻串联接在 18 V 电源两端，电流是多少 A？", answer: 2, steps: ["串联总电阻 9 Ω。", "I=U/R。", "I=18/9=2 A。"] },
      { stem: "6 Ω 与 3 Ω 电阻并联，等效电阻是多少 Ω？", answer: 2, steps: ["1/R=1/6+1/3=1/2。", "取倒数。", "等效电阻 R=2 Ω。"] },
      { stem: "某电阻两端电压 12 V，通过电流 2 A，电阻是多少 Ω？", answer: 6, steps: ["R=U/I。", "代入 12/2。", "电阻为 6 Ω。"] },
      { stem: "用电器两端电压 10 V，通过电流 3 A，电功率是多少 W？", answer: 30, steps: ["P=UI。", "代入 10×3。", "功率为 30 W。"] },
    ],
  }),
  ...numericFamily({
    code: "P-FIELD",
    subject: "physics",
    skill: "electrostatics",
    title: "电场力与场强",
    idea: "电场强度定义为单位正电荷受到的电场力，E=F/q。",
    hints: ["先统一电荷量单位。", "使用 F=qE 或 E=F/q。", "1 μC=10⁻⁶ C。"],
    trap: "微库仑换算成库仑时要乘 10⁻⁶。",
    cases: [
      { stem: "电荷量 2 C 的正电荷在电场中受力 10 N，该处场强大小是多少 N/C？", answer: 5, steps: ["E=F/q。", "代入 10/2。", "E=5 N/C。"] },
      { stem: "场强为 200 N/C，放入电荷量 0.02 C 的正电荷，电场力大小是多少 N？", answer: 4, steps: ["F=qE。", "代入 0.02×200。", "F=4 N。"] },
      { stem: "电荷量 5 C 的电荷受力 15 N，该处场强大小是多少 N/C？", answer: 3, steps: ["E=F/q。", "代入 15/5。", "E=3 N/C。"] },
      { stem: "场强为 50 N/C，电荷量 0.4 C 的正电荷受力大小是多少 N？", answer: 20, steps: ["F=qE。", "代入 0.4×50。", "F=20 N。"] },
    ],
  }),
  ...choiceFamily({
    code: "P-MAGNET",
    subject: "physics",
    skill: "magnetism",
    title: "磁场中带电粒子",
    idea: "洛伦兹力垂直速度时只改变方向，不改变速率。",
    hints: ["洛伦兹力提供向心力。", "列 qvB=mv²/r。", "半径 r=mv/(qB)，周期 T=2πm/(qB)。"],
    trap: "半径与速度成正比，周期在这些条件下与速度无关。",
    cases: [
      { stem: "带电粒子垂直进入匀强磁场，仅受洛伦兹力。速度增大为原来 2 倍，轨道半径变为（　）", options: ["原来的 1/2", "不变", "原来的 2 倍", "原来的 4 倍"], answer: 2, steps: ["r=mv/(qB)。", "其他量不变时 r∝v。", "速度变 2 倍，半径变 2 倍。"] },
      { stem: "同一带电粒子以相同速度垂直进入磁感应强度变为 2 倍的磁场，半径变为（　）", options: ["原来的 1/2", "原来的 2 倍", "原来的 4 倍", "不变"], answer: 0, steps: ["r=mv/(qB)。", "r 与 B 成反比。", "B 变 2 倍，r 变为 1/2。"] },
      { stem: "带电粒子在匀强磁场中做匀速圆周运动，洛伦兹力对粒子做功为（　）", options: ["正功", "负功", "先正后负", "始终为零"], answer: 3, steps: ["洛伦兹力始终垂直瞬时速度。", "垂直力不做功。", "所以做功始终为零。"] },
      { stem: "同一粒子垂直进入同一匀强磁场，速度增大后，其运动周期（　）", options: ["增大", "减小", "不变", "无法判断"], answer: 2, steps: ["周期 T=2πm/(qB)。", "公式中没有速度 v。", "所以周期不变。"] },
    ],
  }),
];

const CHINESE_FAMILIES = [
  ...choiceFamily({
    code: "C-INFO",
    subject: "chinese",
    skill: "information-reading",
    title: "信息类文本推断",
    idea: "推断必须有原文证据，并保持范围、程度和条件不变。",
    hints: ["圈出原文中的限制词。", "警惕“一定、全部、唯一、只要”等绝对化表达。", "选择与原文同义且不扩大范围的选项。"],
    trap: "把“可能、有助于、部分”偷换成“一定、全部”。",
    cases: [
      { stem: "原文：“适量运动可能改善部分青少年的睡眠质量。”据此可推出（　）", options: ["运动一定能治愈失眠", "所有青少年都应高强度运动", "适量运动可能有助于一些青少年睡眠", "睡眠问题只需运动即可解决"], answer: 2, steps: ["保留“适量、可能、部分”三个限制。", "C 没有扩大范围或程度。", "其余选项均绝对化。"] },
      { stem: "原文：“研究样本显示，间隔复习组在一周后的记忆保持率更高。”最稳妥的结论是（　）", options: ["间隔复习在该研究中表现更好", "集中学习永远无效", "所有学科都必须采用同一间隔", "一周后记忆只由复习方式决定"], answer: 0, steps: ["结论只针对该研究样本。", "A 保持原研究范围。", "其他选项加入了“永远、所有、只由”等无依据判断。"] },
      { stem: "原文：“一些城市通过增加树荫步道，缓解了局部区域的夏季热感。”下列正确的是（　）", options: ["树荫步道能消除全球变暖", "所有城市都已采用该方法", "增加树荫步道可能改善局部热感", "城市降温只能依靠植树"], answer: 2, steps: ["原文范围是“一些城市、局部区域”。", "结论强度是“缓解”。", "C 与原意一致。"] },
      { stem: "原文：“数字工具能提高资料检索效率，但不能替代学习者的判断。”理解正确的是（　）", options: ["数字工具会削弱所有判断", "高效检索仍需要人的判断", "有了数字工具就无需学习", "数字工具完全没有价值"], answer: 1, steps: ["原文同时肯定效率和强调判断。", "B 保留这两层意思。", "其余选项只取一面或走向极端。"] },
    ],
  }),
  ...choiceFamily({
    code: "C-ARG",
    subject: "chinese",
    skill: "argument-reading",
    title: "论证方法辨析",
    idea: "判断论证方法要看作者用什么材料、以什么关系证明观点。",
    hints: ["具体人物事件通常是举例论证。", "引用名言、原理通常是引用或道理论证。", "正反两面放在一起是对比论证。"],
    trap: "不要只看材料里出现的词，要看材料在论证中承担的作用。",
    cases: [
      { stem: "作者列举苏炳添长期调整训练细节的事例，证明“突破来自持续优化”。主要运用（　）", options: ["举例论证", "比喻论证", "因果倒置", "反证法"], answer: 0, steps: ["材料是具体人物事例。", "事例用来支持一般观点。", "属于举例论证。"] },
      { stem: "文章引用“学而不思则罔，思而不学则殆”说明学思结合，主要运用（　）", options: ["对比论证", "引用论证", "比喻论证", "类比论证"], answer: 1, steps: ["作者引用经典语句。", "用权威话语支撑观点。", "属于引用论证。"] },
      { stem: "文章将“只追求速度的阅读”与“边读边思考的阅读”效果并列比较，主要运用（　）", options: ["举例论证", "比喻论证", "对比论证", "归谬法"], answer: 2, steps: ["两种阅读方式被并列。", "作者比较二者效果。", "属于对比论证。"] },
      { stem: "作者说“知识不是装进袋子的石块，而是不断生长的树”，主要运用（　）", options: ["比喻论证", "引用论证", "事实论证", "反证法"], answer: 0, steps: ["知识被比作会生长的树。", "用形象关系说明抽象道理。", "属于比喻论证。"] },
    ],
  }),
  ...choiceFamily({
    code: "C-CLASSIC",
    subject: "chinese",
    skill: "classical",
    title: "文言实词语境义",
    idea: "文言实词要放回句子，用现代汉语通顺地替换验证。",
    hints: ["先辨认词性。", "结合上下文人物动作与因果。", "把候选义代回原句检查是否通顺。"],
    trap: "不要只套最熟悉的现代义。",
    cases: [
      { stem: "“假舟楫者，非能水也，而绝江河”中“绝”的意思是（　）", options: ["断绝", "横渡", "极点", "拒绝"], answer: 1, steps: ["句中主语借助船只。", "动作对象是江河。", "“绝”应解释为横渡。"] },
      { stem: "“顾野有麦场”中“顾”的意思是（　）", options: ["照顾", "拜访", "回头看", "顾虑"], answer: 2, steps: ["结合人物当时观察周围环境。", "“顾野”是回头看野外。", "所以选“回头看”。"] },
      { stem: "“秦王复击轲，被八创”中“被”的意思是（　）", options: ["覆盖", "遭受", "同“披”", "被子"], answer: 1, steps: ["“八创”指多处创伤。", "句意是遭受八处伤。", "“被”解释为遭受。"] },
      { stem: "“越国以鄙远，君知其难也”中“鄙”的意思是（　）", options: ["轻视", "边邑，这里作动词把……当边邑", "粗俗", "谦称自己"], answer: 1, steps: ["“远”指远方的郑国。", "这里名词作动词。", "意为把远方国家当作边邑。"] },
    ],
  }),
  ...choiceFamily({
    code: "C-WRITE",
    subject: "chinese",
    skill: "composition",
    title: "材料作文审题",
    idea: "提炼材料中的关键关系，而不是只抓一个表面词语。",
    hints: ["圈出材料里的转折或因果。", "分清材料赞成什么、反对什么。", "中心论点要覆盖材料的核心关系。"],
    trap: "把材料中的某个词当标题，却漏掉词语之间的关系。",
    cases: [
      { stem: "材料：“地图能指路，但真正的方向还要由行走的人判断。”最贴合的立意是（　）", options: ["工具可以替代选择", "善用工具，更要保持自主判断", "拒绝一切技术", "行走比思考重要"], answer: 1, steps: ["材料肯定地图能指路。", "同时强调人要判断方向。", "立意应兼顾工具与主体判断。"] },
      { stem: "材料：“竹子用四年扎根，第五年才快速生长。”最贴合的立意是（　）", options: ["成长只看最后速度", "沉潜积累为突破蓄力", "等待就一定成功", "基础没有结果重要"], answer: 1, steps: ["前四年扎根是积累。", "第五年生长是突破。", "材料强调积累与突破的关系。"] },
      { stem: "材料：“修补旧船的人不仅堵住漏洞，还记录每次破损的位置。”最贴合的立意是（　）", options: ["忘记失败才能前进", "解决当下并从问题中建立经验", "记录比行动重要", "旧事物都应淘汰"], answer: 1, steps: ["堵漏洞对应解决当下。", "记录位置对应积累经验。", "B 完整覆盖两层。"] },
      { stem: "材料：“独奏能展现技巧，合奏更考验倾听。”最贴合的立意是（　）", options: ["个人能力毫无价值", "合作需要能力，也需要倾听与协调", "人多一定力量大", "倾听比行动更重要"], answer: 1, steps: ["材料没有否定独奏技巧。", "合奏增加了倾听要求。", "立意应兼顾个人能力与协作。"] },
    ],
  }),
];

const ENGLISH_FAMILIES = [
  ...choiceFamily({
    code: "E-TENSE",
    subject: "english",
    skill: "tense",
    title: "时态与语态",
    idea: "先找时间参照点，再判断动作的先后和主被动关系。",
    hints: ["圈出时间标志。", "判断动作发生在过去、现在还是过去的过去。", "再检查主语与动作的主被动关系。"],
    trap: "不要看到某个时间词就机械套时态，先判断动作关系。",
    cases: [
      { stem: "I ___ in this city since 2022.", options: ["live", "lived", "have lived", "will live"], answer: 2, steps: ["since 2022 表示从过去持续到现在。", "使用现在完成时。", "选择 have lived。"] },
      { stem: "When I entered the room, they ___ a discussion.", options: ["have", "were having", "will have", "had"], answer: 1, steps: ["entered 是过去时间点。", "当时正在进行讨论。", "使用过去进行时 were having。"] },
      { stem: "The bridge ___ next year.", options: ["completes", "completed", "will be completed", "has completed"], answer: 2, steps: ["next year 指将来。", "桥是被完成。", "使用一般将来时被动语态。"] },
      { stem: "By last Friday, she ___ all the reports.", options: ["finishes", "has finished", "had finished", "will finish"], answer: 2, steps: ["last Friday 是过去参照点。", "完成发生在该点之前。", "使用过去完成时 had finished。"] },
    ],
  }),
  ...choiceFamily({
    code: "E-NONFINITE",
    subject: "english",
    skill: "nonfinite",
    title: "非谓语动词",
    idea: "先找逻辑主语，再判断主动、被动或目的关系。",
    hints: ["确认句中已有谓语动词。", "判断非谓语动作与主语的逻辑关系。", "主动常用 doing，被动常用 done，目的常用 to do。"],
    trap: "不能只凭中文意思选形式，必须检查逻辑主语。",
    cases: [
      { stem: "___ the task, she checked every step again.", options: ["Finish", "Finished", "Having finished", "To finishing"], answer: 2, steps: ["she 主动完成任务。", "完成发生在 checked 之前。", "使用 Having finished。"] },
      { stem: "The book ___ by the teacher is worth reading.", options: ["recommend", "recommended", "recommending", "to recommend"], answer: 1, steps: ["book 与 recommend 是被动关系。", "过去分词作后置定语。", "选择 recommended。"] },
      { stem: "He got up early ___ the first train.", options: ["catch", "caught", "catching", "to catch"], answer: 3, steps: ["早起的目的是赶上火车。", "目的状语用不定式。", "选择 to catch。"] },
      { stem: "___ along the river, we saw many birds.", options: ["Walking", "Walked", "To walked", "Having been walked"], answer: 0, steps: ["we 主动沿河行走。", "动作与 saw 同时或伴随。", "使用 Walking。"] },
    ],
  }),
  ...choiceFamily({
    code: "E-CLAUSE",
    subject: "english",
    skill: "clauses",
    title: "从句连接词",
    idea: "先判断从句类型，再看连接词在从句中是否充当成分。",
    hints: ["找出主句和从句边界。", "判断先行词是人、物、地点还是原因。", "检查从句中缺主语、宾语还是状语。"],
    trap: "关系副词与关系代词不能只看先行词，还要看从句缺什么成分。",
    cases: [
      { stem: "This is the school ___ I studied three years ago.", options: ["which", "where", "what", "who"], answer: 1, steps: ["先行词是 school。", "从句 I studied 缺地点状语。", "使用 where。"] },
      { stem: "The reason ___ he was late was the heavy traffic.", options: ["why", "which", "who", "when"], answer: 0, steps: ["先行词是 reason。", "从句缺原因状语。", "使用 why。"] },
      { stem: "I still remember the day ___ we first met.", options: ["who", "which", "when", "what"], answer: 2, steps: ["先行词是 day。", "从句缺时间状语。", "使用 when。"] },
      { stem: "The student ___ won the prize is my classmate.", options: ["which", "whose", "whom", "who"], answer: 3, steps: ["先行词是人。", "从句缺主语。", "使用 who。"] },
    ],
  }),
  ...choiceFamily({
    code: "E-VOCAB",
    subject: "english",
    skill: "vocabulary",
    title: "语境词义与搭配",
    idea: "先读完整句意，再用固定搭配和语气验证选项。",
    hints: ["不要只看单词长得像不像。", "寻找句中的因果、转折或目的。", "把选项代回句子检查语义和搭配。"],
    trap: "形近词往往词义完全不同，必须回到语境。",
    cases: [
      { stem: "A clear plan can help you ___ your study time more effectively.", options: ["manage", "damage", "imagine", "mention"], answer: 0, steps: ["句意是更有效地安排学习时间。", "manage time 是常见搭配。", "选择 manage。"] },
      { stem: "The scientist remained ___ despite several failed experiments.", options: ["curious", "careless", "silent", "ordinary"], answer: 0, steps: ["despite 表示转折。", "失败后仍保持对研究的好奇。", "curious 最符合语境。"] },
      { stem: "Good notes should be brief but still ___ the key ideas.", options: ["contain", "cancel", "compare", "connect"], answer: 0, steps: ["笔记需要包含关键观点。", "contain 表示“包含”。", "搭配和句意均成立。"] },
      { stem: "Taking a short break may ___ your attention when you feel tired.", options: ["restore", "remove", "reduce", "refuse"], answer: 0, steps: ["疲劳时短暂休息能恢复注意力。", "restore 表示“恢复”。", "选择 restore。"] },
    ],
  }),
  ...choiceFamily({
    code: "E-READ",
    subject: "english",
    skill: "english-reading",
    title: "英语阅读推断",
    idea: "选择能由原文直接支持、且语气不过度的概括。",
    hints: ["找到问题对应的原句。", "关注比较、因果和作者态度。", "排除 always、never、only 等绝对化选项。"],
    trap: "正确选项通常是原文的同义改写，不是常识补充。",
    cases: [
      { stem: "The library extended its opening hours after many students asked for a quieter place to study. Why were the hours extended?", options: ["To sell more books.", "To meet students' study needs.", "To reduce staff numbers.", "To hold sports events."], answer: 1, steps: ["定位原因：students asked for a quieter place to study。", "延长时间是回应学习需求。", "答案是满足学生的学习需要。"] },
      { stem: "Mia tested two routes and chose the longer one because it was safer at night. What mattered most to Mia?", options: ["Speed.", "Cost.", "Safety.", "Scenery."], answer: 2, steps: ["原因从句是 because it was safer。", "longer 说明速度不是首要。", "选择 Safety。"] },
      { stem: "The team failed at first, but each failure revealed a design problem. What can be inferred?", options: ["Failure provided useful feedback.", "The team stopped working.", "The design had no problems.", "Success came without changes."], answer: 0, steps: ["each failure revealed a problem。", "这说明失败带来有效反馈。", "因此可以推断失败提供了有用反馈。"] },
      { stem: "Leo writes a short summary after every lesson, which helps him notice what he still does not understand. What is the main benefit?", options: ["It replaces attending lessons.", "It helps identify learning gaps.", "It makes lessons shorter.", "It removes all mistakes."], answer: 1, steps: ["关键是 notice what he still does not understand。", "对应识别学习漏洞。", "主要好处是帮助发现尚未理解的内容。"] },
    ],
  }),
];

export const GENERATED_QUESTIONS = [
  ...MATH_FAMILIES,
  ...PHYSICS_FAMILIES,
  ...CHINESE_FAMILIES,
  ...ENGLISH_FAMILIES,
];
