export const STORAGE_KEY = 'textile-experience-mvp-v1';

const now = '2026-08-30T18:00:00+08:00';

export const DEMO_DATA = {
  schemaVersion: '0.1.0',
  meta: {
    projectName: '纺织设备老师傅经验萃取系统',
    mode: 'mock',
    activeInterviewId: 'int_demo_live',
    lastSavedAt: now,
  },
  organizations: [
    {
      id: 'org_caresun',
      name: '嘉新国际集团有限公司',
      shortName: '嘉新集团',
      logoAsset: 'assets/caresun-logo.png',
      sites: [
        { id: 'site_yaxin', name: '雅新纺织', workshops: ['一分厂', '三分厂'] },
      ],
    },
  ],
  processes: [
    { id: 'process_foreign_fiber', organizationId: 'org_caresun', name: '异纤', order: 90 },
    { id: 'process_card', organizationId: 'org_caresun', name: '梳棉', order: 20 },
    { id: 'process_spinning', organizationId: 'org_caresun', name: '细纱', order: 50 },
  ],
  equipment: [
    {
      id: 'eq_jwf0019a',
      organizationId: 'org_caresun',
      siteId: 'site_yaxin',
      processId: 'process_foreign_fiber',
      name: '异性纤维分检机',
      category: '异纤机',
      manufacturer: '北京经纬纺机新技术有限公司',
      model: 'JWF0019A',
      versions: ['JLH_2026.01.10.0930'],
      commissionedYear: null,
      assetNo: null,
      photos: [],
      nameplatePhotos: [],
      sourceIds: ['src_manual_jwf', 'src_field_20260722', 'src_fault_report'],
      modules: {
        identity: 'reviewed',
        structure: 'reviewed',
        principle: 'reviewed',
        basicProcessRole: 'reviewed',
        controlSystem: 'partial',
        parameters: 'reviewed',
        normalState: 'partial',
        symptoms: 'partial',
        diagnosis: 'partial',
        repair: 'partial',
        inspectionTechniques: 'partial',
        precautions: 'partial',
        cases: 'partial',
        counterexamples: 'missing',
        expertExperience: 'partial',
        rawSources: 'reviewed',
        knowledgeGaps: 'partial',
      },
      tags: ['异纤', '开清棉', '相机检测', '喷阀'],
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  ],
  experts: [
    {
      id: 'expert_wjz',
      name: '伍建忠',
      organizationId: 'org_caresun',
      siteIds: ['site_yaxin'],
      roles: ['异纤机主管'],
      equipmentIds: ['eq_jwf0019a'],
      experienceYears: null,
      experienceSummary: '清梳联检修工→工序长→设备主管→异纤机专员→异纤机主管',
      consent: 'internal_knowledge_use',
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'expert_demo_b',
      name: '老师傅B（演示）',
      organizationId: 'org_caresun',
      siteIds: ['site_yaxin'],
      roles: ['设备维修'],
      equipmentIds: ['eq_jwf0019a'],
      experienceYears: 18,
      experienceSummary: '用于演示多人观点，不代表真实人员结论',
      consent: 'demo_only',
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  ],
  sources: [
    {
      id: 'src_manual_jwf',
      equipmentIds: ['eq_jwf0019a'],
      type: 'manufacturer_manual',
      title: 'JWF0019A异纤分检机产品说明书',
      fileName: 'JWF0019A异纤分检机产品说明书-20241013(修改).pdf',
      version: '2024-08',
      confidentiality: 'internal',
      importStatus: 'registered',
      notes: '厂家设备基线',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'src_field_20260722',
      equipmentIds: ['eq_jwf0019a'],
      type: 'field_observation',
      title: 'JWF0019A伍建忠实机确认记录',
      fileName: '03_伍建忠实机确认记录.md',
      version: '2026-07-22',
      confidentiality: 'internal',
      importStatus: 'excerpted',
      notes: '现场经验与厂家资料分开保存',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'src_fault_report',
      equipmentIds: ['eq_jwf0019a'],
      type: 'case_report',
      title: 'JWF0019A运维案例与聊天线索清洗报告',
      fileName: '03_运维案例与聊天线索.md',
      version: '2026-07-22',
      confidentiality: 'restricted',
      importStatus: 'excerpted',
      notes: '只使用脱敏后的现象—处置—结果，不公开聊天原文',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  ],
  interviews: [
    {
      id: 'int_demo_live',
      equipmentId: 'eq_jwf0019a',
      expertIds: ['expert_wjz'],
      interviewerId: 'user_wjz',
      knowledgeType: 'fault',
      title: '通讯故障怎么判断（待继续）',
      mode: 'field',
      status: 'in_progress',
      startedAt: '2026-08-30T17:45:00+08:00',
      endedAt: null,
      entries: [
        {
          id: 'entry_live_001',
          kind: 'expert_quote',
          speaker: 'expert_wjz',
          text: '通讯故障一般重启一下就好了。',
          recordedAt: '2026-08-30T17:45:00+08:00',
          attachments: [],
          confirmedByExpert: false,
          linkedQuestionId: null,
          tags: ['通讯', '重启'],
        },
      ],
      activeQuestions: [
        {
          id: 'q_live_001',
          category: 'occurrence_condition',
          priority: 98,
          question: '什么情况下可以先重启？重启前必须先排除哪些安全或硬件问题？',
          reason: '“一般重启”缺使用条件和安全边界',
          triggerText: '一般重启一下',
          status: 'open',
          answerEntryIds: [],
          generatedBy: 'mock',
        },
        {
          id: 'q_live_002',
          category: 'post_repair_validation',
          priority: 96,
          question: '重启后看到什么现象、维持多久，才算真正恢复正常？',
          reason: '“好了”缺可观察的成功标准和观察时长',
          triggerText: '就好了',
          status: 'open',
          answerEntryIds: [],
          generatedBy: 'mock',
        },
        {
          id: 'q_live_003',
          category: 'abnormal_branch',
          priority: 94,
          question: '如果重启后仍报警，或短期恢复后又复发，下一步怎么区分相机、线路和算力盒？',
          reason: '缺失败分支和后续定位方法',
          triggerText: '重启',
          status: 'open',
          answerEntryIds: [],
          generatedBy: 'mock',
        },
      ],
      coverage: {
        symptom: 'partial',
        conditions: 'missing',
        firstJudgment: 'partial',
        judgmentReason: 'missing',
        checkMethod: 'missing',
        normalStandard: 'missing',
        abnormalStandard: 'missing',
        branches: 'missing',
        repair: 'partial',
        safety: 'missing',
        postRepairValidation: 'missing',
        counterexample: 'missing',
      },
      extraction: null,
      followUpInterviewId: null,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'int_demo_primary',
      equipmentId: 'eq_jwf0019a',
      expertIds: ['expert_wjz'],
      interviewerId: 'user_wjz',
      knowledgeType: 'fault',
      title: '主屏画面不刷新第一轮采访',
      mode: 'field',
      status: 'needs_follow_up',
      startedAt: '2026-07-22T09:00:00+08:00',
      endedAt: '2026-07-22T09:28:00+08:00',
      entries: [
        { id: 'entry_p_001', kind: 'expert_quote', speaker: 'expert_wjz', text: '主屏画面卡住一般先重启。', recordedAt: '2026-07-22T09:01:00+08:00', attachments: [], confirmedByExpert: true },
        { id: 'entry_p_002', kind: 'answer', speaker: 'expert_wjz', text: '先看是一个画面不刷新，还是同一个通道前后两个画面一起不刷新。一个画面优先判断相机，两个一起优先判断对应算力盒。', recordedAt: '2026-07-22T09:08:00+08:00', attachments: [], confirmedByExpert: true },
        { id: 'entry_p_003', kind: 'answer', speaker: 'expert_wjz', text: '正常20个相机画面大约0.5到1秒刷新一次，右侧报警也会指出相机或通道。', recordedAt: '2026-07-22T09:14:00+08:00', attachments: [], confirmedByExpert: true },
        { id: 'entry_p_004', kind: 'answer', speaker: 'expert_wjz', text: '两类都可以先按安全流程整机断电重启，断电等20秒再上电，系统和软件大概3分钟起来。短期恢复后反复出现而且越来越频繁，就不能总靠重启。', recordedAt: '2026-07-22T09:21:00+08:00', attachments: [], confirmedByExpert: true },
      ],
      activeQuestions: [],
      coverage: {
        symptom: 'confirmed', conditions: 'partial', firstJudgment: 'confirmed', judgmentReason: 'confirmed',
        checkMethod: 'confirmed', normalStandard: 'confirmed', abnormalStandard: 'confirmed', branches: 'confirmed',
        repair: 'partial', safety: 'partial', postRepairValidation: 'partial', counterexample: 'missing',
      },
      extraction: {
        highValue: ['用单画面/同通道双画面的冻结范围区分相机与算力通道', '正常刷新约0.5～1秒/次', '短期恢复但复发加密时不能长期依赖重启'],
        ordinary: ['上电后Linux和检测软件约3分钟加载'],
        confirmed: ['断电等待20秒', '单画面优先查相机', '配对双画面优先查算力盒'],
        inferred: [],
        ambiguous: ['更换相机/算力盒前的线路排查动作仍不完整'],
        conflicts: ['相机485故障与普通相机故障的厂家正式定义未知'],
        missing: ['重启后的观察时长', '维修更换步骤', '看起来像算力盒但实际是线路的反例'],
        summary: '第一轮已形成故障范围判断骨架，但维修细节和复测时长仍需二次采访。',
      },
      followUpInterviewId: 'int_demo_followup',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'int_demo_followup',
      equipmentId: 'eq_jwf0019a',
      expertIds: ['expert_wjz'],
      interviewerId: 'user_wjz',
      knowledgeType: 'fault',
      title: '主屏画面不刷新二次采访',
      mode: 'desk',
      status: 'completed',
      startedAt: '2026-07-22T15:00:00+08:00',
      endedAt: '2026-07-22T15:19:00+08:00',
      entries: [
        { id: 'entry_f_001', kind: 'answer', speaker: 'expert_wjz', text: '重启前先记录报警对象并确认人员设备安全。恢复后要看20个画面都重新刷新、报警消失、对应通道重新工作。', recordedAt: '2026-07-22T15:04:00+08:00', attachments: [], confirmedByExpert: true },
        { id: 'entry_f_002', kind: 'answer', speaker: 'expert_wjz', text: '单画面复发频率升高，处理对象通常是对应相机；同通道两个画面一起复发，通常是对应算力盒。网口或网线接触也会造成类似现象，所以更换前要查物理连接。', recordedAt: '2026-07-22T15:11:00+08:00', attachments: [], confirmedByExpert: true },
        { id: 'entry_f_003', kind: 'answer', speaker: 'expert_wjz', text: '相机485故障和普通相机故障的正式区别我还不能确定，这个要继续问厂家。', recordedAt: '2026-07-22T15:17:00+08:00', attachments: [], confirmedByExpert: true },
      ],
      activeQuestions: [],
      coverage: {
        symptom: 'confirmed', conditions: 'confirmed', firstJudgment: 'confirmed', judgmentReason: 'confirmed',
        checkMethod: 'confirmed', normalStandard: 'confirmed', abnormalStandard: 'confirmed', branches: 'confirmed',
        repair: 'partial', safety: 'confirmed', postRepairValidation: 'partial', counterexample: 'confirmed',
      },
      extraction: {
        highValue: ['更换相机/算力盒前先排除网口与网线接触问题', '维修后同时看刷新、报警和通道工作三个结果'],
        ordinary: [],
        confirmed: ['相机与算力盒的条件化判断', '重启前先记录报警对象'],
        inferred: [],
        ambiguous: ['复测应持续多久仍未量化'],
        conflicts: [],
        missing: ['485故障正式定义', '相机/算力盒更换SOP', '复测观察时长'],
        summary: '二次采访补齐了线路反例和成功标准，仍保留厂家定义与维修步骤缺口。',
      },
      followUpInterviewId: null,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  ],
  knowledgeItems: [
    {
      id: 'ki_jwf_comm_freeze',
      equipmentId: 'eq_jwf0019a',
      type: 'fault_diagnosis',
      title: '主屏相机画面不刷新',
      summary: '用冻结画面的范围区分相机、线路与算力通道方向。',
      tags: ['通讯', '相机', '算力盒', '画面不刷新', '重启'],
      claims: [
        { id: 'claim_refresh', statement: '正常20个相机画面约0.5～1秒刷新一次', classification: 'expert_experience', verificationStatus: 'expert_confirmed', sourceRefs: [{ sourceId: 'src_field_20260722', locator: '第7节' }], contributorIds: ['expert_wjz'], applicability: { equipmentModels: ['JWF0019A'], softwareVersions: ['JLH_2026.01.10.0930'], conditions: [] }, confidence: 0.85, maturity: 'L3', humanConfirmed: true },
        { id: 'claim_single', statement: '单个画面停止刷新时优先检查对应相机', classification: 'expert_experience', verificationStatus: 'expert_confirmed', sourceRefs: [{ sourceId: 'src_field_20260722', locator: '第7-8节' }], contributorIds: ['expert_wjz'], applicability: { equipmentModels: ['JWF0019A'], softwareVersions: ['JLH_2026.01.10.0930'], conditions: ['其他画面正常'] }, confidence: 0.86, maturity: 'L3', humanConfirmed: true },
        { id: 'claim_pair', statement: '同一计算通道的配对画面同时停止刷新时优先检查对应算力通道/算力盒', classification: 'expert_experience', verificationStatus: 'expert_confirmed', sourceRefs: [{ sourceId: 'src_field_20260722', locator: '第7-8节' }], contributorIds: ['expert_wjz'], applicability: { equipmentModels: ['JWF0019A'], softwareVersions: ['JLH_2026.01.10.0930'], conditions: ['其他画面正常'] }, confidence: 0.86, maturity: 'L3', humanConfirmed: true },
      ],
      diagnosticChain: {
        faultName: '主屏相机画面不刷新',
        symptoms: ['单个画面或同一通道配对画面停止刷新'],
        occurrenceConditions: [],
        frequency: 'unknown',
        severity: 'medium',
        firstDirection: '先按冻结画面的范围区分相机与算力通道',
        firstDirectionReason: '单相机与同通道双相机对应不同的故障范围',
        rootNodeId: 'node_scope',
        nodes: [
          { id: 'node_scope', order: 1, question: '停止刷新的是单个画面，还是同一通道两个配对画面？', why: '先缩小故障范围，避免盲目换件', checkLocation: '主屏20画面区和右侧报警区', checkMethod: '观察刷新范围并核对报警对象', tools: ['设备主屏'], normalState: '20个画面约0.5～1秒刷新一次', abnormalState: '一个或两个配对画面持续停止刷新', branches: { normal: { nextNodeId: null, meaning: '转查历史报警和喷次记录' }, abnormal_single: { nextNodeId: 'node_connection', meaning: '优先查对应相机方向' }, abnormal_pair: { nextNodeId: 'node_connection', meaning: '优先查对应算力通道方向' } }, safetyNotes: [] },
          { id: 'node_connection', order: 2, question: '网口、网线和物理连接是否稳定？', why: '连接问题会伪装成相机或算力盒异常', checkLocation: '交换机、对应网口和线缆', checkMethod: '记录报警后由受训人员检查连接状态', tools: ['目视', '连接记录'], normalState: '连接牢固且无明显接触异常', abnormalState: '松动、接触不良或切换备用网口后恢复', branches: { normal: { nextNodeId: 'node_restart', meaning: '进入安全重启验证' }, abnormal: { nextNodeId: null, meaning: '修复连接后复测' } }, safetyNotes: ['只限受训人员进入电气区域'] },
          { id: 'node_restart', order: 3, question: '按安全流程重启后是否稳定恢复？', why: '区分偶发软件/通讯异常与反复硬件故障', checkLocation: '整机电源、主屏画面和报警区', checkMethod: '停机断电，等待20秒上电，约3分钟后检查刷新、报警和通道', tools: ['设备主屏'], normalState: '画面恢复刷新、报警消失、通道工作', abnormalState: '未恢复或短期恢复后复发加密', branches: { normal: { nextNodeId: null, meaning: '记录本次事件，继续观察' }, abnormal: { nextNodeId: null, meaning: '单画面方向处理相机；配对双画面方向处理算力盒' } }, safetyNotes: ['先确认人员设备安全并防止误启动'] },
        ],
        causes: [
          { id: 'cause_camera', name: '对应相机异常', priority: 1, probability: null, conditions: ['单个画面停止刷新'], verificationNodeIds: ['node_scope', 'node_restart'] },
          { id: 'cause_compute', name: '对应算力盒/计算通道异常', priority: 1, probability: null, conditions: ['同通道两个配对画面同时停止刷新'], verificationNodeIds: ['node_scope', 'node_restart'] },
          { id: 'cause_connection', name: '网口或网线接触问题', priority: 2, probability: null, conditions: ['连接维修后出现或物理链路不稳定'], verificationNodeIds: ['node_connection'] },
        ],
        repairPlans: [
          { id: 'repair_restart', title: '按安全流程整机断电重启', requiredRole: '受训维修人员', preconditions: ['记录报警对象', '确认人员与设备安全'], steps: [{ order: 1, action: '停止检测并断开整机电源', warning: '防止误启动' }, { order: 2, action: '等待20秒', warning: null }, { order: 3, action: '重新上电，等待系统和检测软件加载约3分钟', warning: '软件未加载完成不开始检测' }], resetMethod: '释放屏幕侧小急停并确认检测状态', limitations: ['反复出现且频率升高时不能长期依赖重启'] },
        ],
        postRepairValidation: { method: '检查20个画面刷新、右侧报警和对应通道运行', duration: null, successCriteria: ['画面恢复约0.5～1秒刷新', '报警消失', '对应通道恢复工作'], failureNextStep: '按单画面/双画面范围继续定位相机或算力盒', evidenceRequired: ['恢复后画面或录屏', '报警记录'] },
      },
      status: 'reviewed',
      maturity: 'L3',
      review: { reviewedBy: 'user_wjz', reviewedAt: '2026-07-22T16:00:00+08:00', otherExpertVerified: false },
      searchText: 'JWF0019A 通讯故障 相机画面不刷新 单画面 双画面 算力盒 网线 重启',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    {
      id: 'ki_jwf_parameters',
      equipmentId: 'eq_jwf0019a',
      type: 'parameter',
      title: '当前软件版本与关键监控参数',
      summary: '当前版本JLH_2026.01.10.0930；高温60℃，流速8～12为报警窗口而非强制设定。',
      tags: ['参数', '版本', '高温', '流速', '吹阀'],
      claims: [
        { id: 'claim_temp', statement: '当前现场统一高温报警阈值为60℃', classification: 'measured_data', verificationStatus: 'expert_confirmed', sourceRefs: [{ sourceId: 'src_field_20260722', locator: '参数截图' }], contributorIds: ['expert_wjz'], applicability: { equipmentModels: ['JWF0019A'], softwareVersions: ['JLH_2026.01.10.0930'], conditions: [] }, confidence: 0.95, maturity: 'L3', humanConfirmed: true },
      ],
      diagnosticChain: null,
      status: 'reviewed',
      maturity: 'L3',
      review: { reviewedBy: 'user_wjz', otherExpertVerified: false },
      searchText: 'JWF0019A 参数 60℃ 8-12 400次 JLH_2026.01.10.0930',
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  ],
  reviewTasks: [
    { id: 'task_485', equipmentId: 'eq_jwf0019a', interviewId: 'int_demo_followup', knowledgeItemId: 'ki_jwf_comm_freeze', type: 'follow_up_interview', severity: 'high', title: '确认485故障与普通相机故障的正式区别', questions: ['分别对应哪段通讯链路？', '报警文字和画面范围有何差异？', '各自最终验证方法是什么？'], reason: '当前只有现场现象，没有厂家正式定义', status: 'open', assignee: 'user_wjz', createdAt: now, updatedAt: now, revision: 1 },
    { id: 'task_duration', equipmentId: 'eq_jwf0019a', interviewId: 'int_demo_followup', knowledgeItemId: 'ki_jwf_comm_freeze', type: 'follow_up_interview', severity: 'medium', title: '补充重启后的复测观察时长', questions: ['连续观察多久才能排除短时假恢复？', '需要跨几个生产班次或多少次报警？'], reason: '已有成功标准，但没有时间边界', status: 'open', assignee: 'user_wjz', createdAt: now, updatedAt: now, revision: 1 },
    { id: 'task_repair_sop', equipmentId: 'eq_jwf0019a', interviewId: null, knowledgeItemId: 'ki_jwf_comm_freeze', type: 'source_request', severity: 'medium', title: '补相机与算力盒更换SOP', questions: ['拆装顺序是什么？', '需要哪些工具和防错标记？', '更换后如何加载或校验配置？'], reason: '现有资料只到“更换”，新人无法照做', status: 'open', assignee: 'user_wjz', createdAt: now, updatedAt: now, revision: 1 },
  ],
  auditReports: [],
};

export function cloneDemoData() {
  return JSON.parse(JSON.stringify(DEMO_DATA));
}

export function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return cloneDemoData();
    const parsed = JSON.parse(raw);
    if (parsed.schemaVersion !== DEMO_DATA.schemaVersion) return cloneDemoData();
    return parsed;
  } catch (error) {
    console.warn('本地数据读取失败，已恢复演示数据。', error);
    return cloneDemoData();
  }
}

export function saveState(state) {
  state.meta.lastSavedAt = new Date().toISOString();
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

export function resetState() {
  const fresh = cloneDemoData();
  saveState(fresh);
  return fresh;
}
