import { CURRICULUM_SKILLS } from "./curriculum.js";
import { GENERATED_QUESTIONS } from "./question-bank.js";
import { COVERAGE_QUESTIONS } from "./coverage-bank.js";
import { MATH_DEPTH_QUESTIONS, PHYSICS_DEPTH_QUESTIONS, CHINESE_DEPTH_QUESTIONS, ENGLISH_DEPTH_QUESTIONS } from "./depth-bank.js";
import { getSkillAnalogy } from "./learning-guides.js";

export const SUBJECTS = {
  math: {
    id: "math",
    name: "数学",
    short: "数",
    color: "#4bc6ff",
    accent: "#b9eaff",
    target: 115,
    description: "先抓函数、导数与解析几何",
  },
  physics: {
    id: "physics",
    name: "物理",
    short: "物",
    color: "#8b7cff",
    accent: "#d4ceff",
    target: 75,
    description: "模型识别比盲目计算更重要",
  },
  chinese: {
    id: "chinese",
    name: "语文",
    short: "语",
    color: "#ff9f76",
    accent: "#ffd8c7",
    target: 110,
    description: "阅读有证据，作文有结构",
  },
  english: {
    id: "english",
    name: "英语",
    short: "英",
    color: "#59d6a7",
    accent: "#c0f3df",
    target: 110,
    description: "词块、长难句与限时阅读",
  },
};

export const SKILLS = CURRICULUM_SKILLS;

const CORE_QUESTIONS = [
  {
    id: "M001",
    subject: "math",
    skill: "derivative",
    title: "用导数锁定单调区间",
    stem: "函数 f(x)=x³−3x 的单调递减区间是（　）",
    type: "choice",
    options: ["(−∞,−1)", "(−1,1)", "(1,+∞)", "(−∞,+∞)"],
    answer: 1,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 90,
    hints: [
      "单调性先看导数的正负，不要直接看原函数。",
      "求得 f′(x)=3x²−3，递减对应 f′(x)<0。",
      "3(x−1)(x+1)<0，解集落在两个零点之间。",
    ],
    explanation: {
      idea: "把函数增减转成导数符号问题。",
      steps: ["求导：f′(x)=3x²−3。", "令 3x²−3<0，得到 x²<1。", "因此递减区间为 (−1,1)。"],
      trap: "把 f′(x)>0 当成递减，或只找到导数零点却没有判断区间。",
    },
    errorByChoice: ["符号判断", "", "符号判断", "知识漏洞"],
  },
  {
    id: "M002",
    subject: "math",
    skill: "sequence",
    title: "等差数列求和",
    stem: "等差数列 {aₙ} 中，a₁=3，公差 d=2，则 S₁₀ 等于多少？",
    type: "numeric",
    answer: 120,
    acceptable: ["120"],
    difficulty: 1,
    points: 5,
    estimatedSeconds: 80,
    hints: ["先求第 10 项，或者直接使用含首项和公差的求和公式。", "a₁₀=3+9×2=21。", "S₁₀=10(a₁+a₁₀)÷2。"],
    explanation: {
      idea: "首尾配对求和。",
      steps: ["a₁₀=a₁+9d=21。", "S₁₀=10×(3+21)÷2。", "计算得 120。"],
      trap: "第 10 项只增加 9 个公差，不是 10 个。",
    },
  },
  {
    id: "M003",
    subject: "math",
    skill: "probability",
    title: "不放回抽取",
    stem: "袋中有 2 个红球、3 个蓝球，连续不放回抽取 2 个球，两球都是红球的概率是多少？可填分数或小数。",
    type: "numeric",
    answer: 0.1,
    acceptable: ["0.1", "1/10", "10%"],
    difficulty: 2,
    points: 5,
    estimatedSeconds: 100,
    hints: ["不放回意味着第二次的总球数和红球数都会变化。", "第一次红球概率 2/5，第二次红球概率 1/4。", "两个连续事件同时发生，用乘法。"],
    explanation: {
      idea: "按顺序相乘，体现不放回带来的条件变化。",
      steps: ["第一次取红球：2/5。", "已经取走一个红球后，第二次取红球：1/4。", "(2/5)×(1/4)=1/10。"],
      trap: "第二次仍写 2/5，这是忽略了“不放回”。",
    },
  },
  {
    id: "M004",
    subject: "math",
    skill: "analytic",
    title: "圆的一般方程配方",
    stem: "圆 x²+y²−4x+2y−4=0 的圆心和半径分别是（　）",
    type: "choice",
    options: ["(2,−1)，3", "(−2,1)，3", "(2,1)，√3", "(−2,−1)，√3"],
    answer: 0,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 110,
    hints: ["把 x 项、y 项分别配成完全平方。", "x²−4x=(x−2)²−4；y²+2y=(y+1)²−1。", "标准式为 (x−2)²+(y+1)²=9。"],
    explanation: {
      idea: "一般式通过配方变成标准式。",
      steps: ["x 项配方得到 (x−2)²−4。", "y 项配方得到 (y+1)²−1。", "整理为 (x−2)²+(y+1)²=9，圆心 (2,−1)，半径 3。"],
      trap: "标准式中圆心坐标与括号里的符号相反。",
    },
    errorByChoice: ["", "符号判断", "配方计算", "符号判断"],
  },
  {
    id: "M005",
    subject: "math",
    skill: "trigonometry",
    title: "辅助角公式",
    stem: "函数 y=sin x+cos x 的最大值为（　）",
    type: "choice",
    options: ["1", "√2", "2", "1/2"],
    answer: 1,
    difficulty: 1,
    points: 5,
    estimatedSeconds: 70,
    hints: ["把两个同频三角函数合成一个。", "sin x+cos x=√2·sin(x+π/4)。", "正弦函数的最大值是 1。"],
    explanation: {
      idea: "利用辅助角公式合并。",
      steps: ["提取振幅 √(1²+1²)=√2。", "原式写成 √2·sin(x+π/4)。", "所以最大值是 √2。"],
      trap: "最大值不是两个最大值直接相加，因为 sin x 与 cos x 不能同时取 1。",
    },
    errorByChoice: ["公式遗忘", "", "概念混淆", "计算错误"],
  },
  {
    id: "M006",
    subject: "math",
    skill: "geometry3d",
    title: "空间几何体体积",
    stem: "一个圆锥的底面半径为 3，高为 4，它的体积是（　）",
    type: "choice",
    options: ["12π", "24π", "36π", "48π"],
    answer: 0,
    difficulty: 1,
    points: 5,
    estimatedSeconds: 70,
    hints: ["圆锥体积是同底同高圆柱体积的三分之一。", "V=(1/3)πr²h。", "代入 r=3、h=4。"],
    explanation: {
      idea: "直接识别圆锥体积模型。",
      steps: ["底面积 S=π×3²=9π。", "V=(1/3)Sh。", "V=(1/3)×9π×4=12π。"],
      trap: "漏掉圆锥体积公式里的 1/3。",
    },
    errorByChoice: ["", "计算错误", "公式遗忘", "公式遗忘"],
  },
  {
    id: "M007",
    subject: "math",
    skill: "derivative",
    title: "导数求切线斜率",
    stem: "曲线 y=x²+2x 在点 x=1 处的切线斜率为多少？",
    type: "numeric",
    answer: 4,
    acceptable: ["4"],
    difficulty: 1,
    points: 5,
    estimatedSeconds: 70,
    hints: ["某点切线斜率就是该点的导数值。", "y′=2x+2。", "把 x=1 代入导函数。"],
    explanation: {
      idea: "导数的几何意义是切线斜率。",
      steps: ["求导 y′=2x+2。", "在 x=1 处，y′(1)=2+2。", "斜率为 4。"],
      trap: "把原函数值 y(1) 当成斜率。",
    },
  },
  {
    id: "P001",
    subject: "physics",
    skill: "mechanics",
    title: "受力后求加速度",
    stem: "质量为 2 kg 的物体在水平面上受 10 N 水平拉力，同时受到 2 N 滑动摩擦力。物体的加速度为多少 m/s²？",
    type: "numeric",
    answer: 4,
    acceptable: ["4", "4m/s²", "4m/s2"],
    difficulty: 2,
    points: 6,
    estimatedSeconds: 100,
    hints: ["先求合力，不要把拉力直接代入 F=ma。", "水平方向合力为 10−2=8 N。", "a=F合/m。"],
    explanation: {
      idea: "受力分析后再用牛顿第二定律。",
      steps: ["选物体为研究对象。", "水平合力 F合=10−2=8 N。", "a=8÷2=4 m/s²。"],
      trap: "忽略摩擦力，直接算成 5 m/s²。",
    },
  },
  {
    id: "P002",
    subject: "physics",
    skill: "mechanics",
    title: "平抛运动分解",
    stem: "小球从离地 20 m 高处水平抛出，不计空气阻力，取 g=10 m/s²。小球落地所需时间为多少秒？",
    type: "numeric",
    answer: 2,
    acceptable: ["2", "2s", "2秒"],
    difficulty: 2,
    points: 6,
    estimatedSeconds: 100,
    hints: ["落地时间只由竖直方向运动决定。", "竖直方向是初速度为 0 的自由落体。", "h=(1/2)gt²。"],
    explanation: {
      idea: "平抛运动横竖分解，时间看竖直方向。",
      steps: ["竖直位移 h=20 m。", "20=(1/2)×10×t²。", "t²=4，所以 t=2 s。"],
      trap: "题目没有给水平初速度，因为求落地时间根本不需要它。",
    },
  },
  {
    id: "P003",
    subject: "physics",
    skill: "electricity",
    title: "串联电路",
    stem: "2 Ω 与 4 Ω 两个电阻串联接在 12 V 电源两端，忽略电源内阻，电路电流为多少安？",
    type: "numeric",
    answer: 2,
    acceptable: ["2", "2A", "2安"],
    difficulty: 1,
    points: 6,
    estimatedSeconds: 80,
    hints: ["串联电阻先相加。", "总电阻 R=2+4=6 Ω。", "用 I=U/R。"],
    explanation: {
      idea: "先等效，再用闭合电路的基础关系。",
      steps: ["串联总电阻 R总=6 Ω。", "I=U/R总。", "I=12÷6=2 A。"],
      trap: "把两个电阻按并联公式处理。",
    },
  },
  {
    id: "P004",
    subject: "physics",
    skill: "magnetism",
    title: "带电粒子在磁场中运动",
    stem: "带电粒子以速度 v 垂直进入匀强磁场 B，只受洛伦兹力，做匀速圆周运动的半径是（　）",
    type: "choice",
    options: ["qB/mv", "mv/qB", "qv/mB", "mB/qv"],
    answer: 1,
    difficulty: 3,
    points: 6,
    estimatedSeconds: 120,
    hints: ["洛伦兹力提供向心力。", "列式 qvB=mv²/r。", "等式两边约去一个 v，再解出 r。"],
    explanation: {
      idea: "找到“谁提供向心力”这一模型核心。",
      steps: ["洛伦兹力 F=qvB。", "向心力 F=mv²/r。", "令二者相等，解得 r=mv/(qB)。"],
      trap: "约分或移项时把分子分母颠倒。",
    },
    errorByChoice: ["公式变形", "", "公式变形", "概念混淆"],
  },
  {
    id: "P005",
    subject: "physics",
    skill: "experiment",
    title: "纸带求瞬时速度",
    stem: "打点计时器每 0.02 s 打一个点。相邻两点间距离为 4.0 cm，运动近似匀速，则速度约为多少 m/s？",
    type: "numeric",
    answer: 2,
    acceptable: ["2", "2.0", "2m/s"],
    difficulty: 2,
    points: 6,
    estimatedSeconds: 100,
    hints: ["先统一单位：4.0 cm=0.040 m。", "速度等于位移除以时间。", "v=0.040÷0.02。"],
    explanation: {
      idea: "实验数据处理先统一国际单位。",
      steps: ["将 4.0 cm 化为 0.040 m。", "相邻点的时间间隔为 0.02 s。", "v=0.040/0.02=2.0 m/s。"],
      trap: "厘米没有换成米，导致结果大 100 倍。",
    },
  },
  {
    id: "P006",
    subject: "physics",
    skill: "mechanics",
    title: "动量守恒",
    stem: "质量均为 1 kg 的 A、B 两球在光滑水平面上运动。A 以 4 m/s 撞上静止的 B，碰后两球粘在一起，速度为多少 m/s？",
    type: "numeric",
    answer: 2,
    acceptable: ["2", "2m/s"],
    difficulty: 2,
    points: 6,
    estimatedSeconds: 110,
    hints: ["碰撞过程外力冲量可忽略，系统动量守恒。", "碰前总动量为 1×4+1×0。", "碰后总质量为 2 kg。"],
    explanation: {
      idea: "完全非弹性碰撞仍然守恒动量。",
      steps: ["碰前 p=4 kg·m/s。", "碰后两球共同速度设为 v，总动量为 2v。", "2v=4，得 v=2 m/s。"],
      trap: "粘在一起后质量是两球质量之和。",
    },
  },
  {
    id: "C001",
    subject: "chinese",
    skill: "reading",
    title: "论证方法辨析",
    stem: "文段先列举两项实验结果，再据此说明“短时高强度记忆不如间隔复习稳定”。主要使用了哪种论证方法？",
    type: "choice",
    options: ["比喻论证", "举例论证", "道理论证", "反证法"],
    answer: 1,
    difficulty: 1,
    points: 5,
    estimatedSeconds: 70,
    hints: ["判断依据是作者拿什么材料来证明观点。", "题干明确说“列举两项实验结果”。", "具体事实或案例支撑观点，属于举例论证。"],
    explanation: {
      idea: "从论据的形态判断论证方法。",
      steps: ["实验结果属于具体事实材料。", "具体材料用来支撑一般观点。", "因此是举例论证。"],
      trap: "看到“实验”就误判为道理论证；关键是它作为具体事例出现。",
    },
    errorByChoice: ["概念混淆", "", "概念混淆", "概念混淆"],
  },
  {
    id: "C002",
    subject: "chinese",
    skill: "classical",
    title: "诗歌意象与情感",
    stem: "诗句“梧桐更兼细雨，到黄昏、点点滴滴”最突出的情感基调是（　）",
    type: "choice",
    options: ["豪迈旷达", "清新喜悦", "凄清愁苦", "闲适恬淡"],
    answer: 2,
    difficulty: 1,
    points: 5,
    estimatedSeconds: 60,
    hints: ["抓住“梧桐、细雨、黄昏、点点滴滴”组成的意境。", "这些意象共同营造冷清、绵延的氛围。", "结合《声声慢》的抒情语境判断。"],
    explanation: {
      idea: "意象群共同指向情感，不要只看单个词。",
      steps: ["黄昏与细雨营造低沉环境。", "“点点滴滴”强化愁绪的持续。", "情感基调为凄清愁苦。"],
      trap: "只看到自然景物，没有结合声音、时令和语境。",
    },
    errorByChoice: ["语境忽略", "语境忽略", "", "情感误判"],
  },
  {
    id: "C003",
    subject: "chinese",
    skill: "composition",
    title: "议论文中心论点",
    stem: "材料强调：“真正的成长，不是从不犯错，而是每次犯错后都能看见原因并改变下一次行动。”下列中心论点最贴合材料的是（　）",
    type: "choice",
    options: ["成功必须依靠天赋", "错误本身就等于成长", "复盘让错误转化为成长", "年轻人应该避免一切错误"],
    answer: 2,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 100,
    hints: ["材料的关键词是“犯错后”“看见原因”“改变行动”。", "中心论点要覆盖原因分析和行动改变。", "区分“错误”与“对错误的复盘”。"],
    explanation: {
      idea: "用关键词提炼材料的因果链。",
      steps: ["材料不赞美错误本身。", "它强调分析原因并改变行动。", "因此“复盘让错误转化为成长”最完整。"],
      trap: "把“犯错”偷换成“犯错自然会成长”。",
    },
    errorByChoice: ["偏离材料", "逻辑偷换", "", "绝对化"],
  },
  {
    id: "C004",
    subject: "chinese",
    skill: "reading",
    title: "筛选文本信息",
    stem: "某科普文说：“睡眠并非停止学习，大脑会在睡眠中重新激活白天形成的部分神经连接。”据此可以推出（　）",
    type: "choice",
    options: ["睡得越久成绩一定越好", "睡眠可能帮助巩固部分记忆", "只睡觉不学习也能掌握知识", "所有记忆都会在睡眠中被加强"],
    answer: 1,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 80,
    hints: ["推断不能超过原文范围。", "原文只有“部分神经连接”“重新激活”。", "警惕“一定、只要、所有”等绝对词。"],
    explanation: {
      idea: "把原文信息做同义转换，不扩大范围。",
      steps: ["“重新激活连接”对应记忆巩固。", "“部分”决定结论只能说“可能、部分”。", "因此应选择保留“可能、部分”范围的表述。"],
      trap: "选项中的绝对词常把可能性偷换成必然性。",
    },
    errorByChoice: ["过度推断", "", "过度推断", "范围扩大"],
  },
  {
    id: "E001",
    subject: "english",
    skill: "grammar",
    title: "时态与时间标志",
    stem: "By the time the teacher arrived, the students ___ the experiment.",
    type: "choice",
    options: ["finish", "have finished", "had finished", "will finish"],
    answer: 2,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 70,
    hints: ["找两个过去动作，判断谁发生得更早。", "老师到达是过去时，完成实验发生在此之前。", "过去的过去用 past perfect。"],
    explanation: {
      idea: "By the time + 过去时，主句常用过去完成时表示更早完成。",
      steps: ["arrived 确定参照点在过去。", "完成实验早于 arrived。", "使用 had finished。"],
      trap: "看到“完成”就机械选择现在完成时，没有先找时间参照点。",
    },
    errorByChoice: ["时态基准", "时态基准", "", "时态基准"],
  },
  {
    id: "E002",
    subject: "english",
    skill: "vocabulary",
    title: "语境词义",
    stem: "Regular review helps learners ___ information for a longer time.",
    type: "choice",
    options: ["retain", "remove", "refuse", "replace"],
    answer: 0,
    difficulty: 1,
    points: 5,
    estimatedSeconds: 60,
    hints: ["句意：规律复习帮助学习者把信息保留更长时间。", "寻找表示“保持、记住”的动词。", "retain = keep or continue to have。"],
    explanation: {
      idea: "用句意和搭配共同锁定单词。",
      steps: ["for a longer time 表示持续保留。", "retain information 是常见搭配。", "所以选 retain。"],
      trap: "只看四个词都以 re- 开头，没有回到句意。",
    },
    errorByChoice: ["", "词义混淆", "词义混淆", "词义混淆"],
  },
  {
    id: "E003",
    subject: "english",
    skill: "english-reading",
    title: "阅读推断",
    stem: "A study found that students who tested themselves remembered more than those who only reread their notes. What does the study suggest?",
    type: "choice",
    options: ["Rereading is always useless.", "Self-testing can improve memory.", "Notes should never be used.", "Tests only increase stress."],
    answer: 1,
    difficulty: 2,
    points: 5,
    estimatedSeconds: 90,
    hints: ["比较对象是 self-testing 和 only rereading。", "结果是前者 remembered more。", "选择不绝对、与结果直接对应的概括。"],
    explanation: {
      idea: "阅读推断要贴着比较结果，不加入原文没有的绝对判断。",
      steps: ["自测组记住得更多。", "这支持自测有助于记忆。", "B 的语气 can 也符合研究结论的谨慎表达。"],
      trap: "always、never、only 等绝对词往往超出原文。",
    },
    errorByChoice: ["绝对化", "", "绝对化", "无中生有"],
  },
  {
    id: "E004",
    subject: "english",
    skill: "grammar",
    title: "非谓语动词",
    stem: "___ with a difficult problem, she first broke it into smaller parts.",
    type: "choice",
    options: ["Face", "Facing", "Faced", "To facing"],
    answer: 2,
    difficulty: 3,
    points: 5,
    estimatedSeconds: 100,
    hints: ["识别固定搭配：be faced with。", "省略从句主语和 be 动词后，保留过去分词。", "完整逻辑可理解为 When she was faced with...。"],
    explanation: {
      idea: "非谓语先看逻辑关系，再看固定搭配。",
      steps: ["主句主语是 she。", "she is faced with a problem 是被动/状态结构。", "省略后用 Faced with...。"],
      trap: "受到中文“面对”的影响直接选 Facing，却忽略 be faced with 固定结构。",
    },
    errorByChoice: ["非谓语结构", "固定搭配", "", "形式错误"],
  },
];

const RAW_QUESTIONS = [
  ...CORE_QUESTIONS,
  ...GENERATED_QUESTIONS,
  ...COVERAGE_QUESTIONS,
  ...MATH_DEPTH_QUESTIONS,
  ...PHYSICS_DEPTH_QUESTIONS,
  ...CHINESE_DEPTH_QUESTIONS,
  ...ENGLISH_DEPTH_QUESTIONS,
];

const DIMENSION_SEQUENCE = ["concept", "application", "reasoning", "transfer", "pitfall"];
const skillQuestionIndex = new Map();

function rotateChoiceOptions(question) {
  if (question.type !== "choice") return question;
  const shift = [...question.id].reduce((sum, character) => sum + character.charCodeAt(0), 0) % question.options.length;
  const rotate = (items) => items.map((_, index) => items[(index - shift + items.length) % items.length]);
  return {
    ...question,
    options: rotate(question.options),
    answer: (question.answer + shift) % question.options.length,
    errorByChoice: Array.isArray(question.errorByChoice) ? rotate(question.errorByChoice) : question.errorByChoice,
  };
}

export const QUESTIONS = RAW_QUESTIONS.map((rawQuestion) => {
  const question = rotateChoiceOptions(rawQuestion);
  const index = skillQuestionIndex.get(question.skill) || 0;
  skillQuestionIndex.set(question.skill, index + 1);
  return {
    ...question,
    dimension: question.dimension || DIMENSION_SEQUENCE[index % DIMENSION_SEQUENCE.length],
    explanation: {
      ...question.explanation,
      analogy: question.explanation?.analogy || getSkillAnalogy(question.skill),
    },
  };
});

export const MICRO_LESSONS = [
  {
    id: "L-MATH-DERIVATIVE",
    subject: "math",
    skill: "derivative",
    title: "导数不是公式，是坡度探测器",
    duration: "3 分钟",
    type: "slope",
    frames: [
      {
        eyebrow: "01 · 先看画面",
        title: "函数像一条山路",
        body: "从左往右走，上坡时函数在增加，下坡时函数在减少。",
        note: "先别急着求导，观察“坡度”在说什么。",
      },
      {
        eyebrow: "02 · 把感觉变成数",
        title: "导数就是这一刻的坡度",
        body: "切线向上倾斜，导数为正；切线向下倾斜，导数为负。",
        note: "f′(x)>0 对应增加，f′(x)<0 对应减少。",
      },
      {
        eyebrow: "03 · 找到转折点",
        title: "坡度为 0，可能正在换方向",
        body: "先解 f′(x)=0 找候选分界点，再判断每个区间的正负。",
        note: "“导数等于 0”只是候选点，不能直接断定极值。",
      },
      {
        eyebrow: "04 · 立刻迁移",
        title: "所有单调题都先画符号路线",
        body: "求导 → 找零点 → 分区间 → 判正负 → 写结论。",
        note: "这五步比背十种题型更可靠。",
      },
    ],
  },
  {
    id: "L-PHYSICS-PROJECTILE",
    subject: "physics",
    skill: "mechanics",
    title: "平抛运动：一场同时发生的双线任务",
    duration: "4 分钟",
    type: "projectile",
    frames: [
      {
        eyebrow: "01 · 拆开看",
        title: "小球只走一条曲线，但我们用两条线理解",
        body: "水平方向做匀速直线运动，竖直方向做自由落体运动。",
        note: "分解不是两次运动，而是同一运动的两个方向。",
      },
      {
        eyebrow: "02 · 共同的时钟",
        title: "横竖方向共享同一个时间 t",
        body: "落地时间由高度决定；水平速度只影响飞出多远。",
        note: "问时间先看竖直，问水平位移再带入同一个 t。",
      },
      {
        eyebrow: "03 · 两组公式",
        title: "x=v₀t，h=½gt²",
        body: "先从 h 求 t，再用 x=v₀t 求水平射程。",
        note: "竖直初速度为 0 是平抛成立的关键。",
      },
      {
        eyebrow: "04 · 模型识别",
        title: "看到“水平飞出”就启动分解",
        body: "题目无论换成飞机投物、桌边小球还是运动员跃出，骨架都一样。",
        note: "先认模型，再代数字。",
      },
    ],
  },
];

export const VIDEO_RESOURCES = [
  {
    id: "smartedu",
    subject: "all",
    icon: "🏫",
    tag: "国家平台",
    title: "国家中小学智慧教育平台",
    provider: "教育部官方平台",
    description: "按年级、学科和教材版本选择同步课程，适合准高三系统查漏，不依赖单一老师。",
    bestFor: ["四科同步复习", "教材章节查漏", "免费系统课程"],
    watchTip: "先在平台选择高中、高二或高三，再按正在复习的章节进入课程。",
    url: "https://basic.smartedu.cn/",
  },
  {
    id: "math-yishu",
    subject: "math",
    icon: "📐",
    tag: "体系数学",
    title: "一数 · 高中数学系统课",
    provider: "一数官方课程列表",
    description: "课程按高中数学模块系统整理，适合把函数、数列、立体几何等知识重新串成完整框架。",
    bestFor: ["章节框架", "典型题型", "一轮复习"],
    watchTip: "每次只看当前薄弱知识点，看完立刻回学习岛做 4 道专项题。",
    url: "https://www.bilibili.com/list/14229967?bvid=BV1L142187QT&oid=1556314244",
  },
  {
    id: "physics-liyongle",
    subject: "physics",
    icon: "🧲",
    tag: "公益物理",
    title: "李永乐老师 · 高中物理系列公益课",
    provider: "李永乐老师官方账号",
    description: "强调现象、模型和推导，适合先弄明白物理图景，再回到题目里识别模型。",
    bestFor: ["概念理解", "模型推导", "物理图景"],
    watchTip: "暂停视频，先自己画受力图或运动过程图，再继续看老师的推导。",
    url: "https://www.bilibili.com/list/9458053?bvid=BV1Lz42197T1&oid=1351342373",
  },
  {
    id: "chinese-daijianye",
    subject: "chinese",
    icon: "📜",
    tag: "诗词理解",
    title: "戴建业老师 · 古诗词讲解",
    provider: "戴建业老师官方账号",
    description: "用人物、情境和生活化语言理解诗词，适合提升古诗文兴趣与诗歌鉴赏感受力。",
    bestFor: ["诗歌情境", "作者情感", "鉴赏兴趣"],
    watchTip: "它是诗歌鉴赏拓展，不代替答题规范；看完要用“意象—手法—情感”写三句笔记。",
    url: "https://www.bilibili.com/list/532741557?bvid=BV1z3ByYdEHt&oid=113530129095598",
  },
  {
    id: "english-yingyutu",
    subject: "english",
    icon: "🐰",
    tag: "系统语法",
    title: "英语兔 · 英语语法体系",
    provider: "英语兔官方课程网站",
    description: "把零散语法整理成结构图，适合补句子成分、时态语态和长难句分析的底层框架。",
    bestFor: ["语法框架", "长难句", "阅读基础"],
    watchTip: "每学一个语法点，自己造 2 个句子，再到学习岛做对应英语练习。",
    url: "https://yingyutu.com/",
  },
];

export const DEFAULT_MISSIONS = [
  { id: "mission-weak", type: "practice", subject: "math", title: "抢救最弱点", subtitle: "导数与函数 · 3 题", minutes: 12, xp: 40 },
  { id: "mission-video", type: "lesson", subject: "physics", title: "看懂一个模型", subtitle: "平抛运动动态微课", minutes: 4, xp: 20, lessonId: "L-PHYSICS-PROJECTILE" },
  { id: "mission-review", type: "review", subject: "mixed", title: "消灭到期错题", subtitle: "按记忆节奏复练", minutes: 10, xp: 35 },
  { id: "mission-language", type: "practice", subject: "english", title: "英语保温舱", subtitle: "语法 + 阅读 · 2 题", minutes: 8, xp: 25 },
];

export function getQuestion(id) {
  return QUESTIONS.find((question) => question.id === id);
}

export function getSkill(id) {
  return SKILLS.find((skill) => skill.id === id);
}

export function getLesson(id) {
  return MICRO_LESSONS.find((lesson) => lesson.id === id);
}
